//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aats_installation_tbl
    {
        public System.DateTime effective_date { get; set; }
        public Nullable<double> minimum_ot_hours { get; set; }
        public Nullable<bool> late_no_ot { get; set; }
        public Nullable<int> hours_in_1day_conv { get; set; }
        public Nullable<double> ot_break_hours { get; set; }
    }
}
