//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class astype_tbl
    {
        public string astype_code { get; set; }
        public string astype_descr { get; set; }
        public string astype_abbrv { get; set; }
        public Nullable<bool> astype_show_dtr { get; set; }
    }
}
