//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class authorization_slip_tbl
    {
        public string as_ctrl_no { get; set; }
        public string as_empl_id { get; set; }
        public Nullable<System.DateTime> as_dtr_date { get; set; }
        public Nullable<System.DateTime> as_date_filed { get; set; }
        public string as_am_in { get; set; }
        public string as_am_out { get; set; }
        public string as_pm_in { get; set; }
        public string as_pm_out { get; set; }
        public string reason_code { get; set; }
        public string astype_code { get; set; }
        public string details_remarks { get; set; }
        public Nullable<int> as_under_time { get; set; }
        public string as_comment { get; set; }
        public string as_venue { get; set; }
        public string approval_status { get; set; }
        public Nullable<bool> posting_status { get; set; }
        public string approval_id { get; set; }
    }
}
