//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class authorization_slipt_dtl_tbl
    {
        public string application_nbr { get; set; }
        public System.DateTime as_dtr_date { get; set; }
        public string astype_code { get; set; }
        public string as_am_in { get; set; }
        public string as_am_out { get; set; }
        public string as_pm_in { get; set; }
        public string as_pm_out { get; set; }
        public string reason_code { get; set; }
        public Nullable<decimal> as_under_time { get; set; }
        public string as_comment { get; set; }
        public string as_venue { get; set; }
        public string rcrd_status { get; set; }
        public string empl_id { get; set; }
        public string remove_entry { get; set; }
    }
}
