//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class authorization_wellness_dtl_tbl
    {
        public int id { get; set; }
        public string empl_id { get; set; }
        public string application_nbr { get; set; }
        public System.DateTime date_breakdown { get; set; }
        public System.DateTime parent_date { get; set; }
        public decimal parent_val { get; set; }
        public decimal val { get; set; }
        public string approval_status { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dttm { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
    }
}
