//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class best_in_attendance_hdr_tbl
    {
        public int id { get; set; }
        public string transmittal_nbr { get; set; }
        public Nullable<System.DateTime> period_from { get; set; }
        public Nullable<System.DateTime> period_to { get; set; }
        public string prepared_by { get; set; }
        public string prepared_by_desig { get; set; }
        public string noted_by { get; set; }
        public string noted_by_desig { get; set; }
        public string approved_by { get; set; }
        public string approved_by_desig { get; set; }
        public string submitted_by { get; set; }
        public Nullable<System.DateTime> submitted_dttm { get; set; }
        public string received_by { get; set; }
        public Nullable<System.DateTime> received_dttm { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
    }
}
