//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class best_in_attendance_dtl_tbl
    {
        public int id { get; set; }
        public string transmittal_nbr { get; set; }
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public string department_code { get; set; }
        public string department_name1 { get; set; }
        public string department_short_name { get; set; }
        public string position_long_title { get; set; }
        public string employment_type { get; set; }
        public string remarks { get; set; }
        public string remarks_others { get; set; }
        public Nullable<double> years_in_service { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
    }
}
