//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bio_machine_info_tbl
    {
        public int MachineNumber { get; set; }
        public string ip_address { get; set; }
        public Nullable<int> port_number { get; set; }
        public string bio_location { get; set; }
        public string mac_address { get; set; }
        public Nullable<int> bio_status { get; set; }
        public Nullable<int> extract_type { get; set; }
    }
}
