//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancel_application_tbl
    {
        public int application_id { get; set; }
        public string application_nbr { get; set; }
        public string transaction_code { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_ddtm { get; set; }
        public Nullable<System.DateTime> app_inclusive_date { get; set; }
        public string empl_id { get; set; }
        public string app_purpose { get; set; }
        public string app_place { get; set; }
        public string remarks { get; set; }
        public string justification_remarks { get; set; }
        public string as_type { get; set; }
        public string reason_code { get; set; }
        public string approval_id { get; set; }
        public string approval_status { get; set; }
        public string action_status { get; set; }
    }
}
