//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HRIS_TRKEntities : DbContext
    {
        public HRIS_TRKEntities()
            : base("name=HRIS_TRKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<edocument_trk_tbl> edocument_trk_tbl { get; set; }
    
        public virtual ObjectResult<sp_edocument_trk_tbl_history_Result> sp_edocument_trk_tbl_history(string p_doc_ctrl_nbr, string p_docmnt_type)
        {
            var p_doc_ctrl_nbrParameter = p_doc_ctrl_nbr != null ?
                new ObjectParameter("p_doc_ctrl_nbr", p_doc_ctrl_nbr) :
                new ObjectParameter("p_doc_ctrl_nbr", typeof(string));
    
            var p_docmnt_typeParameter = p_docmnt_type != null ?
                new ObjectParameter("p_docmnt_type", p_docmnt_type) :
                new ObjectParameter("p_docmnt_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_edocument_trk_tbl_history_Result>("sp_edocument_trk_tbl_history", p_doc_ctrl_nbrParameter, p_docmnt_typeParameter);
        }
    }
}
