//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HRIS_ATSEntities : DbContext
    {
        public HRIS_ATSEntities()
            : base("name=HRIS_ATSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vw_leaveadmin_tbl_list> vw_leaveadmin_tbl_list { get; set; }
        public virtual DbSet<vw_lv_ledger_info_curr_vl_sl> vw_lv_ledger_info_curr_vl_sl { get; set; }
        public virtual DbSet<aats_installation_tbl> aats_installation_tbl { get; set; }
        public virtual DbSet<astype_tbl> astype_tbl { get; set; }
        public virtual DbSet<leaveadmin_tbl> leaveadmin_tbl { get; set; }
        public virtual DbSet<leavesubtype_tbl> leavesubtype_tbl { get; set; }
        public virtual DbSet<leavetype_tbl> leavetype_tbl { get; set; }
        public virtual DbSet<timeschedule_tbl> timeschedule_tbl { get; set; }
        public virtual DbSet<traveltype_tbl> traveltype_tbl { get; set; }
        public virtual DbSet<vl_fractionconvertion_tbl> vl_fractionconvertion_tbl { get; set; }
        public virtual DbSet<vl_wop_tbl> vl_wop_tbl { get; set; }
        public virtual DbSet<vlslearned_dailybasis_tbl> vlslearned_dailybasis_tbl { get; set; }
        public virtual DbSet<vw_leaveadmin_dept_list> vw_leaveadmin_dept_list { get; set; }
        public virtual DbSet<vw_leaveadmin_user_list> vw_leaveadmin_user_list { get; set; }
        public virtual DbSet<leave_application_dtl_tbl> leave_application_dtl_tbl { get; set; }
        public virtual DbSet<lv_ledger_dtl_tbl> lv_ledger_dtl_tbl { get; set; }
        public virtual DbSet<vw_lv_ledger_info> vw_lv_ledger_info { get; set; }
        public virtual DbSet<vw_lv_ledger_info_curr> vw_lv_ledger_info_curr { get; set; }
        public virtual DbSet<leave_application_hdr_tbl> leave_application_hdr_tbl { get; set; }
        public virtual DbSet<empl_dtr_dtl_tbl> empl_dtr_dtl_tbl { get; set; }
        public virtual DbSet<vw_all_applications> vw_all_applications { get; set; }
        public virtual DbSet<dtr_overrides_tbl> dtr_overrides_tbl { get; set; }
        public virtual DbSet<leaveappl_dtl_tbl> leaveappl_dtl_tbl { get; set; }
        public virtual DbSet<leaveappl_hdr_tbl> leaveappl_hdr_tbl { get; set; }
        public virtual DbSet<exc_inc_empl_attendance_tbl> exc_inc_empl_attendance_tbl { get; set; }
        public virtual DbSet<lv_ledger_hdr_tbl> lv_ledger_hdr_tbl { get; set; }
        public virtual DbSet<transmittal_leave_dtl_tbl> transmittal_leave_dtl_tbl { get; set; }
        public virtual DbSet<vw_leave_appl_posting_indv_history> vw_leave_appl_posting_indv_history { get; set; }
        public virtual DbSet<leave_application_dtl_cto_tbl> leave_application_dtl_cto_tbl { get; set; }
        public virtual DbSet<transmittal_leave_hdr_tbl> transmittal_leave_hdr_tbl { get; set; }
        public virtual DbSet<leave_application_cancel_tbl> leave_application_cancel_tbl { get; set; }
    
        public virtual ObjectResult<sp_leavesubtype_tbl_list_Result> sp_leavesubtype_tbl_list(string par_leavetype_code)
        {
            var par_leavetype_codeParameter = par_leavetype_code != null ?
                new ObjectParameter("par_leavetype_code", par_leavetype_code) :
                new ObjectParameter("par_leavetype_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_leavesubtype_tbl_list_Result>("sp_leavesubtype_tbl_list", par_leavetype_codeParameter);
        }
    
        public virtual ObjectResult<sp_leavetype_tbl_list_Result> sp_leavetype_tbl_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_leavetype_tbl_list_Result>("sp_leavetype_tbl_list");
        }
    
        public virtual ObjectResult<string> sp_generate_appl_nbr(string p_table_name, Nullable<int> p_charlen, string p_column_name)
        {
            var p_table_nameParameter = p_table_name != null ?
                new ObjectParameter("p_table_name", p_table_name) :
                new ObjectParameter("p_table_name", typeof(string));
    
            var p_charlenParameter = p_charlen.HasValue ?
                new ObjectParameter("p_charlen", p_charlen) :
                new ObjectParameter("p_charlen", typeof(int));
    
            var p_column_nameParameter = p_column_name != null ?
                new ObjectParameter("P_column_name", p_column_name) :
                new ObjectParameter("P_column_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_generate_appl_nbr", p_table_nameParameter, p_charlenParameter, p_column_nameParameter);
        }
    
        public virtual ObjectResult<sp_leaveledger_empl_undertime_Result> sp_leaveledger_empl_undertime(string par_empl_id, string par_month, string par_year)
        {
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_monthParameter = par_month != null ?
                new ObjectParameter("par_month", par_month) :
                new ObjectParameter("par_month", typeof(string));
    
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_leaveledger_empl_undertime_Result>("sp_leaveledger_empl_undertime", par_empl_idParameter, par_monthParameter, par_yearParameter);
        }
    
        public virtual ObjectResult<sp_lv_empl_lst_wout_jo_Result> sp_lv_empl_lst_wout_jo(string par_department_code, string par_employment_type)
        {
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_employment_typeParameter = par_employment_type != null ?
                new ObjectParameter("par_employment_type", par_employment_type) :
                new ObjectParameter("par_employment_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lv_empl_lst_wout_jo_Result>("sp_lv_empl_lst_wout_jo", par_department_codeParameter, par_employment_typeParameter);
        }
    
        public virtual ObjectResult<sp_aats_installation_tbl_list_Result> sp_aats_installation_tbl_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_aats_installation_tbl_list_Result>("sp_aats_installation_tbl_list");
        }
    
        public virtual ObjectResult<sp_astype_tbl_list_Result> sp_astype_tbl_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_astype_tbl_list_Result>("sp_astype_tbl_list");
        }
    
        public virtual ObjectResult<sp_timeschedule_tbl_list_Result> sp_timeschedule_tbl_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_timeschedule_tbl_list_Result>("sp_timeschedule_tbl_list");
        }
    
        public virtual ObjectResult<sp_traveltype_tbl_list_Result> sp_traveltype_tbl_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_traveltype_tbl_list_Result>("sp_traveltype_tbl_list");
        }
    
        public virtual ObjectResult<sp_vlslearned_dailybasis_tbl_List_Result> sp_vlslearned_dailybasis_tbl_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vlslearned_dailybasis_tbl_List_Result>("sp_vlslearned_dailybasis_tbl_List");
        }
    
        public virtual ObjectResult<sp_vl_fractionconvertion_tbl_list_Result> sp_vl_fractionconvertion_tbl_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vl_fractionconvertion_tbl_list_Result>("sp_vl_fractionconvertion_tbl_list");
        }
    
        public virtual ObjectResult<sp_vl_wop_tbl_list_Result> sp_vl_wop_tbl_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vl_wop_tbl_list_Result>("sp_vl_wop_tbl_list");
        }
    
        public virtual ObjectResult<sp_lv_info_Result> sp_lv_info(string par_user_id)
        {
            var par_user_idParameter = par_user_id != null ?
                new ObjectParameter("par_user_id", par_user_id) :
                new ObjectParameter("par_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lv_info_Result>("sp_lv_info", par_user_idParameter);
        }
    
        public virtual ObjectResult<sp_lv_info2_Result> sp_lv_info2(string par_user_id)
        {
            var par_user_idParameter = par_user_id != null ?
                new ObjectParameter("par_user_id", par_user_id) :
                new ObjectParameter("par_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lv_info2_Result>("sp_lv_info2", par_user_idParameter);
        }
    
        public virtual ObjectResult<sp_leavetype_current_bal_Result> sp_leavetype_current_bal(string par_empl_id)
        {
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_leavetype_current_bal_Result>("sp_leavetype_current_bal", par_empl_idParameter);
        }
    
        public virtual ObjectResult<sp_lv_ledger_dtl_tbl_list_Result> sp_lv_ledger_dtl_tbl_list(string par_ledger_ctrl_no)
        {
            var par_ledger_ctrl_noParameter = par_ledger_ctrl_no != null ?
                new ObjectParameter("par_ledger_ctrl_no", par_ledger_ctrl_no) :
                new ObjectParameter("par_ledger_ctrl_no", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lv_ledger_dtl_tbl_list_Result>("sp_lv_ledger_dtl_tbl_list", par_ledger_ctrl_noParameter);
        }
    
        public virtual ObjectResult<sp_lv_ledger_cancel_Result> sp_lv_ledger_cancel(string p_ledger_ctrl_no, string p_leaveledger_date, string p_user_id)
        {
            var p_ledger_ctrl_noParameter = p_ledger_ctrl_no != null ?
                new ObjectParameter("p_ledger_ctrl_no", p_ledger_ctrl_no) :
                new ObjectParameter("p_ledger_ctrl_no", typeof(string));
    
            var p_leaveledger_dateParameter = p_leaveledger_date != null ?
                new ObjectParameter("p_leaveledger_date", p_leaveledger_date) :
                new ObjectParameter("p_leaveledger_date", typeof(string));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lv_ledger_cancel_Result>("sp_lv_ledger_cancel", p_ledger_ctrl_noParameter, p_leaveledger_dateParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_lv_ledger_posted_unposted_Result> sp_lv_ledger_posted_unposted(string par_empl_id, string par_posting_flag)
        {
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_posting_flagParameter = par_posting_flag != null ?
                new ObjectParameter("par_posting_flag", par_posting_flag) :
                new ObjectParameter("par_posting_flag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lv_ledger_posted_unposted_Result>("sp_lv_ledger_posted_unposted", par_empl_idParameter, par_posting_flagParameter);
        }
    
        public virtual ObjectResult<sp_leaveledger_curr_bal_Result> sp_leaveledger_curr_bal(string p_empl_id, string p_year, string p_leavetype_code)
        {
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_yearParameter = p_year != null ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(string));
    
            var p_leavetype_codeParameter = p_leavetype_code != null ?
                new ObjectParameter("p_leavetype_code", p_leavetype_code) :
                new ObjectParameter("p_leavetype_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_leaveledger_curr_bal_Result>("sp_leaveledger_curr_bal", p_empl_idParameter, p_yearParameter, p_leavetype_codeParameter);
        }
    
        public virtual ObjectResult<sp_batch_generate_dtr_emptype_Result> sp_batch_generate_dtr_emptype(string p_dtr_year, string p_dtr_month, string p_empl_id, string p_employment_type, string p_department_code, string p_user_id)
        {
            var p_dtr_yearParameter = p_dtr_year != null ?
                new ObjectParameter("p_dtr_year", p_dtr_year) :
                new ObjectParameter("p_dtr_year", typeof(string));
    
            var p_dtr_monthParameter = p_dtr_month != null ?
                new ObjectParameter("p_dtr_month", p_dtr_month) :
                new ObjectParameter("p_dtr_month", typeof(string));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_employment_typeParameter = p_employment_type != null ?
                new ObjectParameter("p_employment_type", p_employment_type) :
                new ObjectParameter("p_employment_type", typeof(string));
    
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_batch_generate_dtr_emptype_Result>("sp_batch_generate_dtr_emptype", p_dtr_yearParameter, p_dtr_monthParameter, p_empl_idParameter, p_employment_typeParameter, p_department_codeParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_leaveledger_curr_bal2_Result> sp_leaveledger_curr_bal2(string p_empl_id, string p_year, string p_leavetype_code)
        {
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_yearParameter = p_year != null ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(string));
    
            var p_leavetype_codeParameter = p_leavetype_code != null ?
                new ObjectParameter("p_leavetype_code", p_leavetype_code) :
                new ObjectParameter("p_leavetype_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_leaveledger_curr_bal2_Result>("sp_leaveledger_curr_bal2", p_empl_idParameter, p_yearParameter, p_leavetype_codeParameter);
        }
    
        public virtual ObjectResult<sp_ledgerposting_for_approval_list_Result> sp_ledgerposting_for_approval_list(string par_user_id, string par_show_history)
        {
            var par_user_idParameter = par_user_id != null ?
                new ObjectParameter("par_user_id", par_user_id) :
                new ObjectParameter("par_user_id", typeof(string));
    
            var par_show_historyParameter = par_show_history != null ?
                new ObjectParameter("par_show_history", par_show_history) :
                new ObjectParameter("par_show_history", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ledgerposting_for_approval_list_Result>("sp_ledgerposting_for_approval_list", par_user_idParameter, par_show_historyParameter);
        }
    
        public virtual ObjectResult<sp_generate_empl_dtr_Result> sp_generate_empl_dtr(string par_year, string par_month, string par_empl_id, string par_view_type, string par_department_code, string par_employment_type, string par_user_id)
        {
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            var par_monthParameter = par_month != null ?
                new ObjectParameter("par_month", par_month) :
                new ObjectParameter("par_month", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_view_typeParameter = par_view_type != null ?
                new ObjectParameter("par_view_type", par_view_type) :
                new ObjectParameter("par_view_type", typeof(string));
    
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_employment_typeParameter = par_employment_type != null ?
                new ObjectParameter("par_employment_type", par_employment_type) :
                new ObjectParameter("par_employment_type", typeof(string));
    
            var par_user_idParameter = par_user_id != null ?
                new ObjectParameter("par_user_id", par_user_id) :
                new ObjectParameter("par_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_generate_empl_dtr_Result>("sp_generate_empl_dtr", par_yearParameter, par_monthParameter, par_empl_idParameter, par_view_typeParameter, par_department_codeParameter, par_employment_typeParameter, par_user_idParameter);
        }
    
        public virtual ObjectResult<string> sp_batch_generate_dtr_shift(Nullable<int> p_batch_id)
        {
            var p_batch_idParameter = p_batch_id.HasValue ?
                new ObjectParameter("p_batch_id", p_batch_id) :
                new ObjectParameter("p_batch_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_batch_generate_dtr_shift", p_batch_idParameter);
        }
    
        public virtual ObjectResult<sp_generate_empl_dtr_shift_Result> sp_generate_empl_dtr_shift(string par_year, string par_month, string par_empl_id, string par_view_type, string par_department_code, string par_employment_type, string par_user_id)
        {
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            var par_monthParameter = par_month != null ?
                new ObjectParameter("par_month", par_month) :
                new ObjectParameter("par_month", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_view_typeParameter = par_view_type != null ?
                new ObjectParameter("par_view_type", par_view_type) :
                new ObjectParameter("par_view_type", typeof(string));
    
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_employment_typeParameter = par_employment_type != null ?
                new ObjectParameter("par_employment_type", par_employment_type) :
                new ObjectParameter("par_employment_type", typeof(string));
    
            var par_user_idParameter = par_user_id != null ?
                new ObjectParameter("par_user_id", par_user_id) :
                new ObjectParameter("par_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_generate_empl_dtr_shift_Result>("sp_generate_empl_dtr_shift", par_yearParameter, par_monthParameter, par_empl_idParameter, par_view_typeParameter, par_department_codeParameter, par_employment_typeParameter, par_user_idParameter);
        }
    
        public virtual ObjectResult<sp_leaveledger_report_Result> sp_leaveledger_report(string p_empl_id, string p_date_fr, string p_date_to, Nullable<int> p_rep_mode)
        {
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_date_frParameter = p_date_fr != null ?
                new ObjectParameter("p_date_fr", p_date_fr) :
                new ObjectParameter("p_date_fr", typeof(string));
    
            var p_date_toParameter = p_date_to != null ?
                new ObjectParameter("p_date_to", p_date_to) :
                new ObjectParameter("p_date_to", typeof(string));
    
            var p_rep_modeParameter = p_rep_mode.HasValue ?
                new ObjectParameter("p_rep_mode", p_rep_mode) :
                new ObjectParameter("p_rep_mode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_leaveledger_report_Result>("sp_leaveledger_report", p_empl_idParameter, p_date_frParameter, p_date_toParameter, p_rep_modeParameter);
        }
    
        public virtual ObjectResult<sp_dtr_override_approval_list_Result> sp_dtr_override_approval_list(string par_year, string par_month, string par_empl_id, string par_view_type, string par_department_code, string par_user_id, string par_showoption)
        {
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            var par_monthParameter = par_month != null ?
                new ObjectParameter("par_month", par_month) :
                new ObjectParameter("par_month", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_view_typeParameter = par_view_type != null ?
                new ObjectParameter("par_view_type", par_view_type) :
                new ObjectParameter("par_view_type", typeof(string));
    
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_user_idParameter = par_user_id != null ?
                new ObjectParameter("par_user_id", par_user_id) :
                new ObjectParameter("par_user_id", typeof(string));
    
            var par_showoptionParameter = par_showoption != null ?
                new ObjectParameter("par_showoption", par_showoption) :
                new ObjectParameter("par_showoption", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dtr_override_approval_list_Result>("sp_dtr_override_approval_list", par_yearParameter, par_monthParameter, par_empl_idParameter, par_view_typeParameter, par_department_codeParameter, par_user_idParameter, par_showoptionParameter);
        }
    
        public virtual ObjectResult<sp_employee_dtr_override_approval_list_Result> sp_employee_dtr_override_approval_list(string par_department_code, string par_year, string par_month, string par_showoption)
        {
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            var par_monthParameter = par_month != null ?
                new ObjectParameter("par_month", par_month) :
                new ObjectParameter("par_month", typeof(string));
    
            var par_showoptionParameter = par_showoption != null ?
                new ObjectParameter("par_showoption", par_showoption) :
                new ObjectParameter("par_showoption", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_employee_dtr_override_approval_list_Result>("sp_employee_dtr_override_approval_list", par_department_codeParameter, par_yearParameter, par_monthParameter, par_showoptionParameter);
        }
    
        public virtual ObjectResult<sp_department_list_override_approval_Result> sp_department_list_override_approval(string par_year, string par_month)
        {
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            var par_monthParameter = par_month != null ?
                new ObjectParameter("par_month", par_month) :
                new ObjectParameter("par_month", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_department_list_override_approval_Result>("sp_department_list_override_approval", par_yearParameter, par_monthParameter);
        }
    
        public virtual int sp_dtr_override_approved_all(string par_year, string par_month, string par_empl_id, string par_user_id, string par_status)
        {
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            var par_monthParameter = par_month != null ?
                new ObjectParameter("par_month", par_month) :
                new ObjectParameter("par_month", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_user_idParameter = par_user_id != null ?
                new ObjectParameter("par_user_id", par_user_id) :
                new ObjectParameter("par_user_id", typeof(string));
    
            var par_statusParameter = par_status != null ?
                new ObjectParameter("par_status", par_status) :
                new ObjectParameter("par_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dtr_override_approved_all", par_yearParameter, par_monthParameter, par_empl_idParameter, par_user_idParameter, par_statusParameter);
        }
    
        public virtual ObjectResult<sp_dtr_override_list_Result> sp_dtr_override_list(string par_year, string par_month, string par_empl_id, string par_view_type, string par_department_code, string par_user_id)
        {
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            var par_monthParameter = par_month != null ?
                new ObjectParameter("par_month", par_month) :
                new ObjectParameter("par_month", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_view_typeParameter = par_view_type != null ?
                new ObjectParameter("par_view_type", par_view_type) :
                new ObjectParameter("par_view_type", typeof(string));
    
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_user_idParameter = par_user_id != null ?
                new ObjectParameter("par_user_id", par_user_id) :
                new ObjectParameter("par_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dtr_override_list_Result>("sp_dtr_override_list", par_yearParameter, par_monthParameter, par_empl_idParameter, par_view_typeParameter, par_department_codeParameter, par_user_idParameter);
        }
    
        public virtual ObjectResult<sp_approved_overrides_Result> sp_approved_overrides(string p_empl_id, string p_status, string p_year, string p_month, string p_period)
        {
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_statusParameter = p_status != null ?
                new ObjectParameter("p_status", p_status) :
                new ObjectParameter("p_status", typeof(string));
    
            var p_yearParameter = p_year != null ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(string));
    
            var p_monthParameter = p_month != null ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(string));
    
            var p_periodParameter = p_period != null ?
                new ObjectParameter("p_period", p_period) :
                new ObjectParameter("p_period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_approved_overrides_Result>("sp_approved_overrides", p_empl_idParameter, p_statusParameter, p_yearParameter, p_monthParameter, p_periodParameter);
        }
    
        public virtual ObjectResult<sp_approved_timeschedule_Result> sp_approved_timeschedule(string p_empl_id, string p_status, string p_year, string p_month, string p_period, string p_effect_date)
        {
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_statusParameter = p_status != null ?
                new ObjectParameter("p_status", p_status) :
                new ObjectParameter("p_status", typeof(string));
    
            var p_yearParameter = p_year != null ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(string));
    
            var p_monthParameter = p_month != null ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(string));
    
            var p_periodParameter = p_period != null ?
                new ObjectParameter("p_period", p_period) :
                new ObjectParameter("p_period", typeof(string));
    
            var p_effect_dateParameter = p_effect_date != null ?
                new ObjectParameter("p_effect_date", p_effect_date) :
                new ObjectParameter("p_effect_date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_approved_timeschedule_Result>("sp_approved_timeschedule", p_empl_idParameter, p_statusParameter, p_yearParameter, p_monthParameter, p_periodParameter, p_effect_dateParameter);
        }
    
        public virtual ObjectResult<sp_update_dtr_transmittal_add_Result> sp_update_dtr_transmittal_add(string p_dtr_year, string p_dtr_month, string p_empl_id, string p_status)
        {
            var p_dtr_yearParameter = p_dtr_year != null ?
                new ObjectParameter("p_dtr_year", p_dtr_year) :
                new ObjectParameter("p_dtr_year", typeof(string));
    
            var p_dtr_monthParameter = p_dtr_month != null ?
                new ObjectParameter("p_dtr_month", p_dtr_month) :
                new ObjectParameter("p_dtr_month", typeof(string));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_statusParameter = p_status != null ?
                new ObjectParameter("p_status", p_status) :
                new ObjectParameter("p_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_update_dtr_transmittal_add_Result>("sp_update_dtr_transmittal_add", p_dtr_yearParameter, p_dtr_monthParameter, p_empl_idParameter, p_statusParameter);
        }
    
        public virtual ObjectResult<sp_update_dtr_transmittal_remove_Result> sp_update_dtr_transmittal_remove(string p_dtr_year, string p_dtr_month, string p_empl_id, string p_status)
        {
            var p_dtr_yearParameter = p_dtr_year != null ?
                new ObjectParameter("p_dtr_year", p_dtr_year) :
                new ObjectParameter("p_dtr_year", typeof(string));
    
            var p_dtr_monthParameter = p_dtr_month != null ?
                new ObjectParameter("p_dtr_month", p_dtr_month) :
                new ObjectParameter("p_dtr_month", typeof(string));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_statusParameter = p_status != null ?
                new ObjectParameter("p_status", p_status) :
                new ObjectParameter("p_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_update_dtr_transmittal_remove_Result>("sp_update_dtr_transmittal_remove", p_dtr_yearParameter, p_dtr_monthParameter, p_empl_idParameter, p_statusParameter);
        }
    
        public virtual ObjectResult<sp_extract_trk_leave_appl_Result> sp_extract_trk_leave_appl(Nullable<System.DateTime> p_leave_date_from, Nullable<System.DateTime> p_leave_date_to, string p_department_code, string p_empl_id, string p_lv_posting_status, string p_cancel_status, string p_employment_type)
        {
            var p_leave_date_fromParameter = p_leave_date_from.HasValue ?
                new ObjectParameter("p_leave_date_from", p_leave_date_from) :
                new ObjectParameter("p_leave_date_from", typeof(System.DateTime));
    
            var p_leave_date_toParameter = p_leave_date_to.HasValue ?
                new ObjectParameter("p_leave_date_to", p_leave_date_to) :
                new ObjectParameter("p_leave_date_to", typeof(System.DateTime));
    
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_lv_posting_statusParameter = p_lv_posting_status != null ?
                new ObjectParameter("p_lv_posting_status", p_lv_posting_status) :
                new ObjectParameter("p_lv_posting_status", typeof(string));
    
            var p_cancel_statusParameter = p_cancel_status != null ?
                new ObjectParameter("p_cancel_status", p_cancel_status) :
                new ObjectParameter("p_cancel_status", typeof(string));
    
            var p_employment_typeParameter = p_employment_type != null ?
                new ObjectParameter("p_employment_type", p_employment_type) :
                new ObjectParameter("p_employment_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_extract_trk_leave_appl_Result>("sp_extract_trk_leave_appl", p_leave_date_fromParameter, p_leave_date_toParameter, p_department_codeParameter, p_empl_idParameter, p_lv_posting_statusParameter, p_cancel_statusParameter, p_employment_typeParameter);
        }
    
        public virtual ObjectResult<sp_check_shiftsched_Result> sp_check_shiftsched(string par_year, string par_month, string par_empl_id)
        {
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            var par_monthParameter = par_month != null ?
                new ObjectParameter("par_month", par_month) :
                new ObjectParameter("par_month", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_check_shiftsched_Result>("sp_check_shiftsched", par_yearParameter, par_monthParameter, par_empl_idParameter);
        }
    
        public virtual ObjectResult<sp_time_schedule_empl_hdr_tbl_Result> sp_time_schedule_empl_hdr_tbl(string par_empl_id)
        {
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_time_schedule_empl_hdr_tbl_Result>("sp_time_schedule_empl_hdr_tbl", par_empl_idParameter);
        }
    
        public virtual ObjectResult<sp_time_schedule_empl_tbl1_Result> sp_time_schedule_empl_tbl1(string par_empl_id, string par_month, string par_year, Nullable<System.DateTime> par_effective_date)
        {
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_monthParameter = par_month != null ?
                new ObjectParameter("par_month", par_month) :
                new ObjectParameter("par_month", typeof(string));
    
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            var par_effective_dateParameter = par_effective_date.HasValue ?
                new ObjectParameter("par_effective_date", par_effective_date) :
                new ObjectParameter("par_effective_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_time_schedule_empl_tbl1_Result>("sp_time_schedule_empl_tbl1", par_empl_idParameter, par_monthParameter, par_yearParameter, par_effective_dateParameter);
        }
    
        public virtual ObjectResult<sp_forgot_punch_rep_Result> sp_forgot_punch_rep(string p_rep_year, string p_rep_month, Nullable<System.DateTime> p_rep_date_from, Nullable<System.DateTime> p_rep_date_to, string p_empl_id)
        {
            var p_rep_yearParameter = p_rep_year != null ?
                new ObjectParameter("p_rep_year", p_rep_year) :
                new ObjectParameter("p_rep_year", typeof(string));
    
            var p_rep_monthParameter = p_rep_month != null ?
                new ObjectParameter("p_rep_month", p_rep_month) :
                new ObjectParameter("p_rep_month", typeof(string));
    
            var p_rep_date_fromParameter = p_rep_date_from.HasValue ?
                new ObjectParameter("p_rep_date_from", p_rep_date_from) :
                new ObjectParameter("p_rep_date_from", typeof(System.DateTime));
    
            var p_rep_date_toParameter = p_rep_date_to.HasValue ?
                new ObjectParameter("p_rep_date_to", p_rep_date_to) :
                new ObjectParameter("p_rep_date_to", typeof(System.DateTime));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_forgot_punch_rep_Result>("sp_forgot_punch_rep", p_rep_yearParameter, p_rep_monthParameter, p_rep_date_fromParameter, p_rep_date_toParameter, p_empl_idParameter);
        }
    
        public virtual ObjectResult<sp_exc_inc_empl_attendance_tbl_list_Result> sp_exc_inc_empl_attendance_tbl_list(string p_option_type)
        {
            var p_option_typeParameter = p_option_type != null ?
                new ObjectParameter("p_option_type", p_option_type) :
                new ObjectParameter("p_option_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_exc_inc_empl_attendance_tbl_list_Result>("sp_exc_inc_empl_attendance_tbl_list", p_option_typeParameter);
        }
    
        public virtual ObjectResult<sp_generate_key_Result> sp_generate_key(string p_table_name, string p_key_field, Nullable<int> p_key_size)
        {
            var p_table_nameParameter = p_table_name != null ?
                new ObjectParameter("p_table_name", p_table_name) :
                new ObjectParameter("p_table_name", typeof(string));
    
            var p_key_fieldParameter = p_key_field != null ?
                new ObjectParameter("p_key_field", p_key_field) :
                new ObjectParameter("p_key_field", typeof(string));
    
            var p_key_sizeParameter = p_key_size.HasValue ?
                new ObjectParameter("p_key_size", p_key_size) :
                new ObjectParameter("p_key_size", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_generate_key_Result>("sp_generate_key", p_table_nameParameter, p_key_fieldParameter, p_key_sizeParameter);
        }
    
        public virtual ObjectResult<sp_extract_best_attendance_Result> sp_extract_best_attendance(Nullable<System.DateTime> p_period_from, Nullable<System.DateTime> p_period_to, string p_department_code, string p_employment_type, string p_empl_id)
        {
            var p_period_fromParameter = p_period_from.HasValue ?
                new ObjectParameter("p_period_from", p_period_from) :
                new ObjectParameter("p_period_from", typeof(System.DateTime));
    
            var p_period_toParameter = p_period_to.HasValue ?
                new ObjectParameter("p_period_to", p_period_to) :
                new ObjectParameter("p_period_to", typeof(System.DateTime));
    
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_employment_typeParameter = p_employment_type != null ?
                new ObjectParameter("p_employment_type", p_employment_type) :
                new ObjectParameter("p_employment_type", typeof(string));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_extract_best_attendance_Result>("sp_extract_best_attendance", p_period_fromParameter, p_period_toParameter, p_department_codeParameter, p_employment_typeParameter, p_empl_idParameter);
        }
    
        public virtual ObjectResult<sp_extract_trk_leave_appl_lvl1_final_appr_Result> sp_extract_trk_leave_appl_lvl1_final_appr(Nullable<System.DateTime> p_leave_date_from, Nullable<System.DateTime> p_leave_date_to, string p_department_code, string p_empl_id, string p_lv_posting_status, string p_cancel_status, string p_employment_type)
        {
            var p_leave_date_fromParameter = p_leave_date_from.HasValue ?
                new ObjectParameter("p_leave_date_from", p_leave_date_from) :
                new ObjectParameter("p_leave_date_from", typeof(System.DateTime));
    
            var p_leave_date_toParameter = p_leave_date_to.HasValue ?
                new ObjectParameter("p_leave_date_to", p_leave_date_to) :
                new ObjectParameter("p_leave_date_to", typeof(System.DateTime));
    
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_lv_posting_statusParameter = p_lv_posting_status != null ?
                new ObjectParameter("p_lv_posting_status", p_lv_posting_status) :
                new ObjectParameter("p_lv_posting_status", typeof(string));
    
            var p_cancel_statusParameter = p_cancel_status != null ?
                new ObjectParameter("p_cancel_status", p_cancel_status) :
                new ObjectParameter("p_cancel_status", typeof(string));
    
            var p_employment_typeParameter = p_employment_type != null ?
                new ObjectParameter("p_employment_type", p_employment_type) :
                new ObjectParameter("p_employment_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_extract_trk_leave_appl_lvl1_final_appr_Result>("sp_extract_trk_leave_appl_lvl1_final_appr", p_leave_date_fromParameter, p_leave_date_toParameter, p_department_codeParameter, p_empl_idParameter, p_lv_posting_statusParameter, p_cancel_statusParameter, p_employment_typeParameter);
        }
    
        public virtual ObjectResult<sp_lv_empl_lst_wout_jo_yr_mt_Result> sp_lv_empl_lst_wout_jo_yr_mt(string par_department_code, string par_employment_type, string par_year, string par_month)
        {
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_employment_typeParameter = par_employment_type != null ?
                new ObjectParameter("par_employment_type", par_employment_type) :
                new ObjectParameter("par_employment_type", typeof(string));
    
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            var par_monthParameter = par_month != null ?
                new ObjectParameter("par_month", par_month) :
                new ObjectParameter("par_month", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lv_empl_lst_wout_jo_yr_mt_Result>("sp_lv_empl_lst_wout_jo_yr_mt", par_department_codeParameter, par_employment_typeParameter, par_yearParameter, par_monthParameter);
        }
    
        public virtual ObjectResult<sp_lv_ledger_earn_history_tbl_list_Result> sp_lv_ledger_earn_history_tbl_list(string par_gen_year, string par_gen_month, string par_department_code, string par_earning_type)
        {
            var par_gen_yearParameter = par_gen_year != null ?
                new ObjectParameter("par_gen_year", par_gen_year) :
                new ObjectParameter("par_gen_year", typeof(string));
    
            var par_gen_monthParameter = par_gen_month != null ?
                new ObjectParameter("par_gen_month", par_gen_month) :
                new ObjectParameter("par_gen_month", typeof(string));
    
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_earning_typeParameter = par_earning_type != null ?
                new ObjectParameter("par_earning_type", par_earning_type) :
                new ObjectParameter("par_earning_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lv_ledger_earn_history_tbl_list_Result>("sp_lv_ledger_earn_history_tbl_list", par_gen_yearParameter, par_gen_monthParameter, par_department_codeParameter, par_earning_typeParameter);
        }
    
        public virtual ObjectResult<sp_lv_ledger_generate_earning_Result> sp_lv_ledger_generate_earning(string par_year, string par_month, string par_department_code, string par_empl_id, string par_user_id, string par_earning_type)
        {
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            var par_monthParameter = par_month != null ?
                new ObjectParameter("par_month", par_month) :
                new ObjectParameter("par_month", typeof(string));
    
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_user_idParameter = par_user_id != null ?
                new ObjectParameter("par_user_id", par_user_id) :
                new ObjectParameter("par_user_id", typeof(string));
    
            var par_earning_typeParameter = par_earning_type != null ?
                new ObjectParameter("par_earning_type", par_earning_type) :
                new ObjectParameter("par_earning_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lv_ledger_generate_earning_Result>("sp_lv_ledger_generate_earning", par_yearParameter, par_monthParameter, par_department_codeParameter, par_empl_idParameter, par_user_idParameter, par_earning_typeParameter);
        }
    
        public virtual int sp_approve_cancellation(string p_empl_id, string p_dtr_date, string p_user_id)
        {
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_dtr_dateParameter = p_dtr_date != null ?
                new ObjectParameter("p_dtr_date", p_dtr_date) :
                new ObjectParameter("p_dtr_date", typeof(string));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_approve_cancellation", p_empl_idParameter, p_dtr_dateParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_transmittal_leave_hdr_tbl_list_Result> sp_transmittal_leave_hdr_tbl_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_transmittal_leave_hdr_tbl_list_Result>("sp_transmittal_leave_hdr_tbl_list");
        }
    
        public virtual ObjectResult<sp_transmittal_leave_dtl_tbl_list_Result> sp_transmittal_leave_dtl_tbl_list(string par_doc_ctrl_nbr, Nullable<System.DateTime> par_approved_period_from, Nullable<System.DateTime> par_approved_period_to, string par_department_code, string par_employment_type, string par_view_mode)
        {
            var par_doc_ctrl_nbrParameter = par_doc_ctrl_nbr != null ?
                new ObjectParameter("par_doc_ctrl_nbr", par_doc_ctrl_nbr) :
                new ObjectParameter("par_doc_ctrl_nbr", typeof(string));
    
            var par_approved_period_fromParameter = par_approved_period_from.HasValue ?
                new ObjectParameter("par_approved_period_from", par_approved_period_from) :
                new ObjectParameter("par_approved_period_from", typeof(System.DateTime));
    
            var par_approved_period_toParameter = par_approved_period_to.HasValue ?
                new ObjectParameter("par_approved_period_to", par_approved_period_to) :
                new ObjectParameter("par_approved_period_to", typeof(System.DateTime));
    
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_employment_typeParameter = par_employment_type != null ?
                new ObjectParameter("par_employment_type", par_employment_type) :
                new ObjectParameter("par_employment_type", typeof(string));
    
            var par_view_modeParameter = par_view_mode != null ?
                new ObjectParameter("par_view_mode", par_view_mode) :
                new ObjectParameter("par_view_mode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_transmittal_leave_dtl_tbl_list_Result>("sp_transmittal_leave_dtl_tbl_list", par_doc_ctrl_nbrParameter, par_approved_period_fromParameter, par_approved_period_toParameter, par_department_codeParameter, par_employment_typeParameter, par_view_modeParameter);
        }
    
        public virtual ObjectResult<sp_get_empl_employment_type_Result> sp_get_empl_employment_type(string par_empl_id)
        {
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_empl_employment_type_Result>("sp_get_empl_employment_type", par_empl_idParameter);
        }
    }
}
