//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HRIS_DTREntities : DbContext
    {
        public HRIS_DTREntities()
            : base("name=HRIS_DTREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bio_log_info_tbl> bio_log_info_tbl { get; set; }
        public virtual DbSet<dtr_processed_files_tbl> dtr_processed_files_tbl { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<bio_extract_stg_tbl> bio_extract_stg_tbl { get; set; }
        public virtual DbSet<bio_machine_info_tbl> bio_machine_info_tbl { get; set; }
        public virtual DbSet<vw_personnelnames_tbl_DTR> vw_personnelnames_tbl_DTR { get; set; }
        public virtual DbSet<dtr_from_bio_tbl> dtr_from_bio_tbl { get; set; }
        public virtual DbSet<dtr_bio_extract2> dtr_bio_extract2 { get; set; }
    
        public virtual int sp_adjust_biodata_2dtr_stg(Nullable<long> p_process_nbr, string p_user_id)
        {
            var p_process_nbrParameter = p_process_nbr.HasValue ?
                new ObjectParameter("p_process_nbr", p_process_nbr) :
                new ObjectParameter("p_process_nbr", typeof(long));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_adjust_biodata_2dtr_stg", p_process_nbrParameter, p_user_idParameter);
        }
    
        public virtual int sp_adjust_biodata_2dtr_stg_shift(Nullable<long> p_process_nbr, string p_user_id)
        {
            var p_process_nbrParameter = p_process_nbr.HasValue ?
                new ObjectParameter("p_process_nbr", p_process_nbr) :
                new ObjectParameter("p_process_nbr", typeof(long));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_adjust_biodata_2dtr_stg_shift", p_process_nbrParameter, p_user_idParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_as_alerts_Result> sp_as_alerts(string p_empl_id, string p_year, string p_month)
        {
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_yearParameter = p_year != null ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(string));
    
            var p_monthParameter = p_month != null ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_as_alerts_Result>("sp_as_alerts", p_empl_idParameter, p_yearParameter, p_monthParameter);
        }
    
        public virtual ObjectResult<string> sp_batch_generate_dtr(Nullable<int> p_batch_id)
        {
            var p_batch_idParameter = p_batch_id.HasValue ?
                new ObjectParameter("p_batch_id", p_batch_id) :
                new ObjectParameter("p_batch_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_batch_generate_dtr", p_batch_idParameter);
        }
    
        public virtual ObjectResult<sp_bio_log_info_tbl_ip_Result> sp_bio_log_info_tbl_ip(string p_ip)
        {
            var p_ipParameter = p_ip != null ?
                new ObjectParameter("p_ip", p_ip) :
                new ObjectParameter("p_ip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_bio_log_info_tbl_ip_Result>("sp_bio_log_info_tbl_ip", p_ipParameter);
        }
    
        public virtual ObjectResult<sp_bio_machine_info_tbl_Result> sp_bio_machine_info_tbl(Nullable<int> p_bio_status, string p_ip_address, Nullable<int> p_MachineNumber)
        {
            var p_bio_statusParameter = p_bio_status.HasValue ?
                new ObjectParameter("p_bio_status", p_bio_status) :
                new ObjectParameter("p_bio_status", typeof(int));
    
            var p_ip_addressParameter = p_ip_address != null ?
                new ObjectParameter("p_ip_address", p_ip_address) :
                new ObjectParameter("p_ip_address", typeof(string));
    
            var p_MachineNumberParameter = p_MachineNumber.HasValue ?
                new ObjectParameter("p_MachineNumber", p_MachineNumber) :
                new ObjectParameter("p_MachineNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_bio_machine_info_tbl_Result>("sp_bio_machine_info_tbl", p_bio_statusParameter, p_ip_addressParameter, p_MachineNumberParameter);
        }
    
        public virtual ObjectResult<sp_compare_dtr_bio_extract_Result> sp_compare_dtr_bio_extract(string p_date, string p_terminal)
        {
            var p_dateParameter = p_date != null ?
                new ObjectParameter("p_date", p_date) :
                new ObjectParameter("p_date", typeof(string));
    
            var p_terminalParameter = p_terminal != null ?
                new ObjectParameter("p_terminal", p_terminal) :
                new ObjectParameter("p_terminal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_compare_dtr_bio_extract_Result>("sp_compare_dtr_bio_extract", p_dateParameter, p_terminalParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_delete_bio_extract_stg_tbl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_bio_extract_stg_tbl");
        }
    
        public virtual int sp_delete_bio_extract_stg_tbl_bydateAndMachine(Nullable<int> p_machine_number, Nullable<System.DateTime> p_startdate, Nullable<System.DateTime> p_lastdate)
        {
            var p_machine_numberParameter = p_machine_number.HasValue ?
                new ObjectParameter("p_machine_number", p_machine_number) :
                new ObjectParameter("p_machine_number", typeof(int));
    
            var p_startdateParameter = p_startdate.HasValue ?
                new ObjectParameter("p_startdate", p_startdate) :
                new ObjectParameter("p_startdate", typeof(System.DateTime));
    
            var p_lastdateParameter = p_lastdate.HasValue ?
                new ObjectParameter("p_lastdate", p_lastdate) :
                new ObjectParameter("p_lastdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_bio_extract_stg_tbl_bydateAndMachine", p_machine_numberParameter, p_startdateParameter, p_lastdateParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_dtr_from_bio_tbl_dates_Result> sp_dtr_from_bio_tbl_dates(Nullable<int> p_year, Nullable<int> p_month)
        {
            var p_yearParameter = p_year.HasValue ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(int));
    
            var p_monthParameter = p_month.HasValue ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dtr_from_bio_tbl_dates_Result>("sp_dtr_from_bio_tbl_dates", p_yearParameter, p_monthParameter);
        }
    
        public virtual ObjectResult<sp_dtr_from_bio_tbl_list2_Result> sp_dtr_from_bio_tbl_list2(string p_empl_id, string p_year, string p_month)
        {
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_yearParameter = p_year != null ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(string));
    
            var p_monthParameter = p_month != null ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dtr_from_bio_tbl_list2_Result>("sp_dtr_from_bio_tbl_list2", p_empl_idParameter, p_yearParameter, p_monthParameter);
        }
    
        public virtual ObjectResult<sp_dtr_from_bio_tbl_update_Result> sp_dtr_from_bio_tbl_update(Nullable<System.DateTime> p_dtr_date, string p_empl_id, string p_processed_by_user, string p_field_to_up, string p_field_value, string p_field_to_up2, string p_field_value2, string p_flag)
        {
            var p_dtr_dateParameter = p_dtr_date.HasValue ?
                new ObjectParameter("p_dtr_date", p_dtr_date) :
                new ObjectParameter("p_dtr_date", typeof(System.DateTime));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_processed_by_userParameter = p_processed_by_user != null ?
                new ObjectParameter("p_processed_by_user", p_processed_by_user) :
                new ObjectParameter("p_processed_by_user", typeof(string));
    
            var p_field_to_upParameter = p_field_to_up != null ?
                new ObjectParameter("p_field_to_up", p_field_to_up) :
                new ObjectParameter("p_field_to_up", typeof(string));
    
            var p_field_valueParameter = p_field_value != null ?
                new ObjectParameter("p_field_value", p_field_value) :
                new ObjectParameter("p_field_value", typeof(string));
    
            var p_field_to_up2Parameter = p_field_to_up2 != null ?
                new ObjectParameter("p_field_to_up2", p_field_to_up2) :
                new ObjectParameter("p_field_to_up2", typeof(string));
    
            var p_field_value2Parameter = p_field_value2 != null ?
                new ObjectParameter("p_field_value2", p_field_value2) :
                new ObjectParameter("p_field_value2", typeof(string));
    
            var p_flagParameter = p_flag != null ?
                new ObjectParameter("p_flag", p_flag) :
                new ObjectParameter("p_flag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dtr_from_bio_tbl_update_Result>("sp_dtr_from_bio_tbl_update", p_dtr_dateParameter, p_empl_idParameter, p_processed_by_userParameter, p_field_to_upParameter, p_field_valueParameter, p_field_to_up2Parameter, p_field_value2Parameter, p_flagParameter);
        }
    
        public virtual ObjectResult<string> sp_getfile_list(string p_location)
        {
            var p_locationParameter = p_location != null ?
                new ObjectParameter("p_location", p_location) :
                new ObjectParameter("p_location", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_getfile_list", p_locationParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_insert_bio_extract_stg_tbl(Nullable<int> p_MachineNumber, Nullable<int> p_IndRegID, string p_DateTimeRecord, Nullable<int> p_VerifyMode, Nullable<int> p_InOutMode, Nullable<int> p_WorkCode, Nullable<System.DateTime> p_DateOnlyRecord, Nullable<System.DateTime> p_TimeOnlyRecord, Nullable<int> p_ExtractType)
        {
            var p_MachineNumberParameter = p_MachineNumber.HasValue ?
                new ObjectParameter("p_MachineNumber", p_MachineNumber) :
                new ObjectParameter("p_MachineNumber", typeof(int));
    
            var p_IndRegIDParameter = p_IndRegID.HasValue ?
                new ObjectParameter("p_IndRegID", p_IndRegID) :
                new ObjectParameter("p_IndRegID", typeof(int));
    
            var p_DateTimeRecordParameter = p_DateTimeRecord != null ?
                new ObjectParameter("p_DateTimeRecord", p_DateTimeRecord) :
                new ObjectParameter("p_DateTimeRecord", typeof(string));
    
            var p_VerifyModeParameter = p_VerifyMode.HasValue ?
                new ObjectParameter("p_VerifyMode", p_VerifyMode) :
                new ObjectParameter("p_VerifyMode", typeof(int));
    
            var p_InOutModeParameter = p_InOutMode.HasValue ?
                new ObjectParameter("p_InOutMode", p_InOutMode) :
                new ObjectParameter("p_InOutMode", typeof(int));
    
            var p_WorkCodeParameter = p_WorkCode.HasValue ?
                new ObjectParameter("p_WorkCode", p_WorkCode) :
                new ObjectParameter("p_WorkCode", typeof(int));
    
            var p_DateOnlyRecordParameter = p_DateOnlyRecord.HasValue ?
                new ObjectParameter("p_DateOnlyRecord", p_DateOnlyRecord) :
                new ObjectParameter("p_DateOnlyRecord", typeof(System.DateTime));
    
            var p_TimeOnlyRecordParameter = p_TimeOnlyRecord.HasValue ?
                new ObjectParameter("p_TimeOnlyRecord", p_TimeOnlyRecord) :
                new ObjectParameter("p_TimeOnlyRecord", typeof(System.DateTime));
    
            var p_ExtractTypeParameter = p_ExtractType.HasValue ?
                new ObjectParameter("p_ExtractType", p_ExtractType) :
                new ObjectParameter("p_ExtractType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_bio_extract_stg_tbl", p_MachineNumberParameter, p_IndRegIDParameter, p_DateTimeRecordParameter, p_VerifyModeParameter, p_InOutModeParameter, p_WorkCodeParameter, p_DateOnlyRecordParameter, p_TimeOnlyRecordParameter, p_ExtractTypeParameter);
        }
    
        public virtual int sp_insert_bio_log_info_tbl(Nullable<System.DateTime> p_log_date, Nullable<int> p_MachineNumber, string p_ip_address, string p_bio_location, string p_log_descr, Nullable<int> p_log_status, Nullable<long> p_prc_nbr, string p_prc_parameters)
        {
            var p_log_dateParameter = p_log_date.HasValue ?
                new ObjectParameter("p_log_date", p_log_date) :
                new ObjectParameter("p_log_date", typeof(System.DateTime));
    
            var p_MachineNumberParameter = p_MachineNumber.HasValue ?
                new ObjectParameter("p_MachineNumber", p_MachineNumber) :
                new ObjectParameter("p_MachineNumber", typeof(int));
    
            var p_ip_addressParameter = p_ip_address != null ?
                new ObjectParameter("p_ip_address", p_ip_address) :
                new ObjectParameter("p_ip_address", typeof(string));
    
            var p_bio_locationParameter = p_bio_location != null ?
                new ObjectParameter("p_bio_location", p_bio_location) :
                new ObjectParameter("p_bio_location", typeof(string));
    
            var p_log_descrParameter = p_log_descr != null ?
                new ObjectParameter("p_log_descr", p_log_descr) :
                new ObjectParameter("p_log_descr", typeof(string));
    
            var p_log_statusParameter = p_log_status.HasValue ?
                new ObjectParameter("p_log_status", p_log_status) :
                new ObjectParameter("p_log_status", typeof(int));
    
            var p_prc_nbrParameter = p_prc_nbr.HasValue ?
                new ObjectParameter("p_prc_nbr", p_prc_nbr) :
                new ObjectParameter("p_prc_nbr", typeof(long));
    
            var p_prc_parametersParameter = p_prc_parameters != null ?
                new ObjectParameter("p_prc_parameters", p_prc_parameters) :
                new ObjectParameter("p_prc_parameters", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_bio_log_info_tbl", p_log_dateParameter, p_MachineNumberParameter, p_ip_addressParameter, p_bio_locationParameter, p_log_descrParameter, p_log_statusParameter, p_prc_nbrParameter, p_prc_parametersParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_timefilter_bioextract_Result> sp_timefilter_bioextract()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_timefilter_bioextract_Result>("sp_timefilter_bioextract");
        }
    
        public virtual int sp_update_bio_log_info_tbl(Nullable<System.DateTime> p_log_date, Nullable<int> p_MachineNumber, string p_ip_address, Nullable<long> p_prc_nbr, string p_prc_parameters)
        {
            var p_log_dateParameter = p_log_date.HasValue ?
                new ObjectParameter("p_log_date", p_log_date) :
                new ObjectParameter("p_log_date", typeof(System.DateTime));
    
            var p_MachineNumberParameter = p_MachineNumber.HasValue ?
                new ObjectParameter("p_MachineNumber", p_MachineNumber) :
                new ObjectParameter("p_MachineNumber", typeof(int));
    
            var p_ip_addressParameter = p_ip_address != null ?
                new ObjectParameter("p_ip_address", p_ip_address) :
                new ObjectParameter("p_ip_address", typeof(string));
    
            var p_prc_nbrParameter = p_prc_nbr.HasValue ?
                new ObjectParameter("p_prc_nbr", p_prc_nbr) :
                new ObjectParameter("p_prc_nbr", typeof(long));
    
            var p_prc_parametersParameter = p_prc_parameters != null ?
                new ObjectParameter("p_prc_parameters", p_prc_parameters) :
                new ObjectParameter("p_prc_parameters", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_bio_log_info_tbl", p_log_dateParameter, p_MachineNumberParameter, p_ip_addressParameter, p_prc_nbrParameter, p_prc_parametersParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<sp_upload_datfile_all_Result> sp_upload_datfile_all(string p_year, string p_month, string p_user_id)
        {
            var p_yearParameter = p_year != null ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(string));
    
            var p_monthParameter = p_month != null ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(string));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_upload_datfile_all_Result>("sp_upload_datfile_all", p_yearParameter, p_monthParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_upload_file_from_bio_to_stg_Result> sp_upload_file_from_bio_to_stg(string p_location, string p_filename, string p_year, string p_month, string p_user_id)
        {
            var p_locationParameter = p_location != null ?
                new ObjectParameter("p_location", p_location) :
                new ObjectParameter("p_location", typeof(string));
    
            var p_filenameParameter = p_filename != null ?
                new ObjectParameter("p_filename", p_filename) :
                new ObjectParameter("p_filename", typeof(string));
    
            var p_yearParameter = p_year != null ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(string));
    
            var p_monthParameter = p_month != null ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(string));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_upload_file_from_bio_to_stg_Result>("sp_upload_file_from_bio_to_stg", p_locationParameter, p_filenameParameter, p_yearParameter, p_monthParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_upload_file_from_bio_to_stg_extracted_Result> sp_upload_file_from_bio_to_stg_extracted(string p_location, string p_filename, string p_year, string p_month, string p_user_id)
        {
            var p_locationParameter = p_location != null ?
                new ObjectParameter("p_location", p_location) :
                new ObjectParameter("p_location", typeof(string));
    
            var p_filenameParameter = p_filename != null ?
                new ObjectParameter("p_filename", p_filename) :
                new ObjectParameter("p_filename", typeof(string));
    
            var p_yearParameter = p_year != null ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(string));
    
            var p_monthParameter = p_month != null ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(string));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_upload_file_from_bio_to_stg_extracted_Result>("sp_upload_file_from_bio_to_stg_extracted", p_locationParameter, p_filenameParameter, p_yearParameter, p_monthParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_dtr_from_bio_tbl_list3_Result> sp_dtr_from_bio_tbl_list3(string p_empl_id, string p_year, string p_month)
        {
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_yearParameter = p_year != null ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(string));
    
            var p_monthParameter = p_month != null ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dtr_from_bio_tbl_list3_Result>("sp_dtr_from_bio_tbl_list3", p_empl_idParameter, p_yearParameter, p_monthParameter);
        }
    
        public virtual ObjectResult<sp_process_biodata_2dtr_stg_in_perEmpl_id_Result> sp_process_biodata_2dtr_stg_in_perEmpl_id(Nullable<long> p_process_nbr, string p_empl_id, string p_user_id)
        {
            var p_process_nbrParameter = p_process_nbr.HasValue ?
                new ObjectParameter("p_process_nbr", p_process_nbr) :
                new ObjectParameter("p_process_nbr", typeof(long));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_process_biodata_2dtr_stg_in_perEmpl_id_Result>("sp_process_biodata_2dtr_stg_in_perEmpl_id", p_process_nbrParameter, p_empl_idParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_process_biodata_2dtr_stg_out_perEmpl_id_Result> sp_process_biodata_2dtr_stg_out_perEmpl_id(Nullable<long> p_process_nbr, string p_empl_id, string p_user_id)
        {
            var p_process_nbrParameter = p_process_nbr.HasValue ?
                new ObjectParameter("p_process_nbr", p_process_nbr) :
                new ObjectParameter("p_process_nbr", typeof(long));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_process_biodata_2dtr_stg_out_perEmpl_id_Result>("sp_process_biodata_2dtr_stg_out_perEmpl_id", p_process_nbrParameter, p_empl_idParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_process_biodata_2dtr_stg_perEmpl_id_Result> sp_process_biodata_2dtr_stg_perEmpl_id(Nullable<long> p_process_nbr, string p_empl_id, string p_user_id)
        {
            var p_process_nbrParameter = p_process_nbr.HasValue ?
                new ObjectParameter("p_process_nbr", p_process_nbr) :
                new ObjectParameter("p_process_nbr", typeof(long));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_process_biodata_2dtr_stg_perEmpl_id_Result>("sp_process_biodata_2dtr_stg_perEmpl_id", p_process_nbrParameter, p_empl_idParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_process_biodata_2dtr_stg_shift_perEmpl_id_Result> sp_process_biodata_2dtr_stg_shift_perEmpl_id(Nullable<long> p_process_nbr, string p_empl_id, string p_user_id)
        {
            var p_process_nbrParameter = p_process_nbr.HasValue ?
                new ObjectParameter("p_process_nbr", p_process_nbr) :
                new ObjectParameter("p_process_nbr", typeof(long));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_process_biodata_2dtr_stg_shift_perEmpl_id_Result>("sp_process_biodata_2dtr_stg_shift_perEmpl_id", p_process_nbrParameter, p_empl_idParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_update_dtr_bio_extract_biotype_Result> sp_update_dtr_bio_extract_biotype(string p_empl_id, string p_bio_date, string p_bio_time, string p_bio_terminal, string p_bio_type_or, string p_bio_type, string p_updated_dttm, string p_updated_userby)
        {
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_bio_dateParameter = p_bio_date != null ?
                new ObjectParameter("p_bio_date", p_bio_date) :
                new ObjectParameter("p_bio_date", typeof(string));
    
            var p_bio_timeParameter = p_bio_time != null ?
                new ObjectParameter("p_bio_time", p_bio_time) :
                new ObjectParameter("p_bio_time", typeof(string));
    
            var p_bio_terminalParameter = p_bio_terminal != null ?
                new ObjectParameter("p_bio_terminal", p_bio_terminal) :
                new ObjectParameter("p_bio_terminal", typeof(string));
    
            var p_bio_type_orParameter = p_bio_type_or != null ?
                new ObjectParameter("p_bio_type_or", p_bio_type_or) :
                new ObjectParameter("p_bio_type_or", typeof(string));
    
            var p_bio_typeParameter = p_bio_type != null ?
                new ObjectParameter("p_bio_type", p_bio_type) :
                new ObjectParameter("p_bio_type", typeof(string));
    
            var p_updated_dttmParameter = p_updated_dttm != null ?
                new ObjectParameter("p_updated_dttm", p_updated_dttm) :
                new ObjectParameter("p_updated_dttm", typeof(string));
    
            var p_updated_userbyParameter = p_updated_userby != null ?
                new ObjectParameter("p_updated_userby", p_updated_userby) :
                new ObjectParameter("p_updated_userby", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_update_dtr_bio_extract_biotype_Result>("sp_update_dtr_bio_extract_biotype", p_empl_idParameter, p_bio_dateParameter, p_bio_timeParameter, p_bio_terminalParameter, p_bio_type_orParameter, p_bio_typeParameter, p_updated_dttmParameter, p_updated_userbyParameter);
        }
    
        public virtual ObjectResult<sp_dtr_from_bio_tbl_list_Result> sp_dtr_from_bio_tbl_list(Nullable<System.DateTime> p_dtr_date, string p_empl_id_ao)
        {
            var p_dtr_dateParameter = p_dtr_date.HasValue ?
                new ObjectParameter("p_dtr_date", p_dtr_date) :
                new ObjectParameter("p_dtr_date", typeof(System.DateTime));
    
            var p_empl_id_aoParameter = p_empl_id_ao != null ?
                new ObjectParameter("p_empl_id_ao", p_empl_id_ao) :
                new ObjectParameter("p_empl_id_ao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dtr_from_bio_tbl_list_Result>("sp_dtr_from_bio_tbl_list", p_dtr_dateParameter, p_empl_id_aoParameter);
        }
    
        public virtual ObjectResult<sp_dtr_bio_extract_list_Result> sp_dtr_bio_extract_list(string par_empl_id, string par_bio_date)
        {
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_bio_dateParameter = par_bio_date != null ?
                new ObjectParameter("par_bio_date", par_bio_date) :
                new ObjectParameter("par_bio_date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dtr_bio_extract_list_Result>("sp_dtr_bio_extract_list", par_empl_idParameter, par_bio_dateParameter);
        }
    
        public virtual ObjectResult<sp_process_biodata_2dtr_stg_Result> sp_process_biodata_2dtr_stg(Nullable<long> p_process_nbr, string p_user_id)
        {
            var p_process_nbrParameter = p_process_nbr.HasValue ?
                new ObjectParameter("p_process_nbr", p_process_nbr) :
                new ObjectParameter("p_process_nbr", typeof(long));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_process_biodata_2dtr_stg_Result>("sp_process_biodata_2dtr_stg", p_process_nbrParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_process_biodata_2dtr_stg_in_Result> sp_process_biodata_2dtr_stg_in(Nullable<long> p_process_nbr, string p_user_id)
        {
            var p_process_nbrParameter = p_process_nbr.HasValue ?
                new ObjectParameter("p_process_nbr", p_process_nbr) :
                new ObjectParameter("p_process_nbr", typeof(long));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_process_biodata_2dtr_stg_in_Result>("sp_process_biodata_2dtr_stg_in", p_process_nbrParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_process_biodata_2dtr_stg_out_Result> sp_process_biodata_2dtr_stg_out(Nullable<long> p_process_nbr, string p_user_id)
        {
            var p_process_nbrParameter = p_process_nbr.HasValue ?
                new ObjectParameter("p_process_nbr", p_process_nbr) :
                new ObjectParameter("p_process_nbr", typeof(long));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_process_biodata_2dtr_stg_out_Result>("sp_process_biodata_2dtr_stg_out", p_process_nbrParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_process_biodata_2dtr_stg_shift_pagro_pasian_Result> sp_process_biodata_2dtr_stg_shift_pagro_pasian(Nullable<long> p_process_nbr, string p_user_id)
        {
            var p_process_nbrParameter = p_process_nbr.HasValue ?
                new ObjectParameter("p_process_nbr", p_process_nbr) :
                new ObjectParameter("p_process_nbr", typeof(long));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_process_biodata_2dtr_stg_shift_pagro_pasian_Result>("sp_process_biodata_2dtr_stg_shift_pagro_pasian", p_process_nbrParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_process_biodata_2dtr_stg_shift_Result> sp_process_biodata_2dtr_stg_shift(Nullable<long> p_process_nbr, string p_user_id)
        {
            var p_process_nbrParameter = p_process_nbr.HasValue ?
                new ObjectParameter("p_process_nbr", p_process_nbr) :
                new ObjectParameter("p_process_nbr", typeof(long));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_process_biodata_2dtr_stg_shift_Result>("sp_process_biodata_2dtr_stg_shift", p_process_nbrParameter, p_user_idParameter);
        }
    
        public virtual ObjectResult<sp_extract_process_Result> sp_extract_process(string p_empl_id, string p_start_date, string p_last_date, string p_filename, string p_year, string p_month, string p_user_id, Nullable<int> p_extract_type)
        {
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            var p_start_dateParameter = p_start_date != null ?
                new ObjectParameter("p_start_date", p_start_date) :
                new ObjectParameter("p_start_date", typeof(string));
    
            var p_last_dateParameter = p_last_date != null ?
                new ObjectParameter("p_last_date", p_last_date) :
                new ObjectParameter("p_last_date", typeof(string));
    
            var p_filenameParameter = p_filename != null ?
                new ObjectParameter("p_filename", p_filename) :
                new ObjectParameter("p_filename", typeof(string));
    
            var p_yearParameter = p_year != null ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(string));
    
            var p_monthParameter = p_month != null ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(string));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            var p_extract_typeParameter = p_extract_type.HasValue ?
                new ObjectParameter("p_extract_type", p_extract_type) :
                new ObjectParameter("p_extract_type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_extract_process_Result>("sp_extract_process", p_empl_idParameter, p_start_dateParameter, p_last_dateParameter, p_filenameParameter, p_yearParameter, p_monthParameter, p_user_idParameter, p_extract_typeParameter);
        }
    
        public virtual ObjectResult<sp_time_out_ot_list_Result> sp_time_out_ot_list(string par_empl_id, Nullable<System.DateTime> par_bio_date)
        {
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_bio_dateParameter = par_bio_date.HasValue ?
                new ObjectParameter("par_bio_date", par_bio_date) :
                new ObjectParameter("par_bio_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_time_out_ot_list_Result>("sp_time_out_ot_list", par_empl_idParameter, par_bio_dateParameter);
        }
    }
}
