//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coc_earnings_dtl_tbl
    {
        public string applnbr { get; set; }
        public System.DateTime coc_ot_date { get; set; }
        public string coc_ot_hrs { get; set; }
    }
}
