//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtr_transmittal_dtl_tbl
    {
        public string transmittal_nbr { get; set; }
        public string approval_status { get; set; }
        public string empl_id { get; set; }
        public Nullable<System.DateTime> frst_qcna_posted_ddtm { get; set; }
        public string frst_qcna_posted_by { get; set; }
        public Nullable<System.DateTime> sec_qcna_posted_ddtm { get; set; }
        public string sec_qcna_posted_by { get; set; }
        public string post_status { get; set; }
        public string remarks { get; set; }
    }
}
