//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtr_transmittal_hdr_tbl
    {
        public string transmittal_nbr { get; set; }
        public Nullable<System.DateTime> transmittal_date { get; set; }
        public string dtr_year { get; set; }
        public string dtr_month { get; set; }
        public string view_type { get; set; }
        public string transmittal_descr { get; set; }
        public string department_code { get; set; }
        public string addressto_id { get; set; }
        public string requestor_id { get; set; }
        public string approval_status { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by { get; set; }
        public string remarks { get; set; }
        public string transmittal_type { get; set; }
    }
}
