//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtr_overrides_tbl
    {
        public string dtr_order_no { get; set; }
        public string empl_id { get; set; }
        public System.DateTime dtr_date { get; set; }
        public string time_in_am { get; set; }
        public string time_out_am { get; set; }
        public string time_in_pm { get; set; }
        public string time_out_pm { get; set; }
        public string ts_code { get; set; }
        public Nullable<int> under_Time { get; set; }
        public string under_Time_remarks { get; set; }
        public string remarks_details { get; set; }
        public string time_ot_hris { get; set; }
        public Nullable<double> time_days_equi { get; set; }
        public Nullable<double> time_hours_equi { get; set; }
        public Nullable<double> time_ot_payable { get; set; }
        public Nullable<decimal> no_of_as { get; set; }
        public Nullable<decimal> no_of_ob { get; set; }
        public Nullable<decimal> no_of_lv { get; set; }
        public string created_by_user { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string updated_by_user { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string remarks_override { get; set; }
        public string reason_override { get; set; }
        public string approval_status { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_dttm { get; set; }
    }
}
