//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtr_bio_extract2
    {
        public string empl_id { get; set; }
        public string bio_date { get; set; }
        public string bio_time { get; set; }
        public string bio_terminal { get; set; }
        public string bio_etype { get; set; }
        public string bio_filler1 { get; set; }
        public string bio_filler2 { get; set; }
        public Nullable<long> process_nbr { get; set; }
        public string uploaded_by { get; set; }
        public Nullable<System.DateTime> uploaded_dttm { get; set; }
    }
}
