//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtr_empl_national_hdr_tbl
    {
        public string dtr_ctrl_nbr { get; set; }
        public string dtr_year { get; set; }
        public string dtr_month { get; set; }
        public string department_code { get; set; }
        public string empl_id { get; set; }
        public Nullable<System.DateTime> created_ddtm { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_ddtm { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> approved_1st_ddtm { get; set; }
        public string approved_1st_by { get; set; }
        public Nullable<System.DateTime> approved_2nd_ddtm { get; set; }
        public string approved_2nd_by { get; set; }
        public string status_1st { get; set; }
        public string status_2nd { get; set; }
    }
}
