//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtr_processed_files_tbl
    {
        public long process_nbr { get; set; }
        public string result_value { get; set; }
        public string result_value_descr { get; set; }
        public string result_filename { get; set; }
        public string processed_by { get; set; }
        public Nullable<System.DateTime> processed_dttm { get; set; }
    }
}
