//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtr_empl_national_dtl_tbl
    {
        public string dtr_ctrl_nbr { get; set; }
        public System.DateTime dtr_date { get; set; }
        public string time_in_am { get; set; }
        public string time_out_am { get; set; }
        public string time_in_pm { get; set; }
        public string time_out_pm { get; set; }
        public string ts_code { get; set; }
        public Nullable<int> under_Time { get; set; }
        public string under_Time_remarks { get; set; }
        public string remarks_details { get; set; }
        public string time_ot_hris { get; set; }
        public Nullable<double> time_days_equi { get; set; }
        public Nullable<double> time_hours_equi { get; set; }
        public Nullable<double> time_ot_payable { get; set; }
        public Nullable<decimal> no_of_as { get; set; }
        public Nullable<decimal> no_of_ob { get; set; }
        public Nullable<decimal> no_of_lv { get; set; }
        public string time_in_am_flag { get; set; }
        public string time_out_am_flag { get; set; }
        public string time_in_pm_flag { get; set; }
        public string time_out_pm_flag { get; set; }
    }
}
