//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empl_dtr_transmital_update
    {
        public string dtr_empl_id { get; set; }
        public string dtr_year { get; set; }
        public string dtr_month { get; set; }
        public string dtr_frst_qcna_posted_ddtm { get; set; }
        public string dtr_sec_qcna_posted_ddtm { get; set; }
    }
}
