//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empl_aoh_render_hdr_tbl
    {
        public string aoh_ctrl_nbr { get; set; }
        public string dtr_year { get; set; }
        public string dtr_month { get; set; }
        public string department_code { get; set; }
        public string empl_id { get; set; }
        public Nullable<System.DateTime> created_ddtm { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_ddtm { get; set; }
        public string updated_by { get; set; }
        public string noted_by_empl_id { get; set; }
        public string requested_by_empl_id { get; set; }
        public string recomappr_empl_id { get; set; }
        public string approved_by_empl_id { get; set; }
        public string approval_status { get; set; }
        public string aoh_remakrs { get; set; }
    }
}
