//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empl_dtr_hdr_tbl
    {
        public string dtr_order_no { get; set; }
        public string dtr_year { get; set; }
        public string dtr_month { get; set; }
        public string department_code { get; set; }
        public string approval_status { get; set; }
        public string approval_id { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string remarks { get; set; }
        public string empl_id { get; set; }
        public Nullable<System.DateTime> created_ddtm { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_ddtm { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> frst_qcna_posted_ddtm { get; set; }
        public string frst_qcna_posted_by { get; set; }
        public Nullable<System.DateTime> sec_qcna_posted_ddtm { get; set; }
        public string sec_qcna_posted_by { get; set; }
        public string post_status { get; set; }
    }
}
