//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empl_aoh_render_dtl_tbl
    {
        public string aoh_ctrl_nbr { get; set; }
        public string empl_id { get; set; }
        public string dtr_date_concatenated { get; set; }
        public string aoh_reason { get; set; }
    }
}
