//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fl_plan_dtl_rep_tbl
    {
        public string fl_plan_rep_ctrlno { get; set; }
        public string fl_plan_rep_year { get; set; }
        public string empl_id { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string user_created_dttm { get; set; }
    }
}
