//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leavesubtype_tbl
    {
        public string leavetype_code { get; set; }
        public string leavesubtype_code { get; set; }
        public string leavesubtype_descr { get; set; }
    }
}
