//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leave_application_disapproved_tbl
    {
        public int id { get; set; }
        public string empl_id { get; set; }
        public string leave_ctrlno { get; set; }
        public Nullable<System.DateTime> disapproved_date { get; set; }
        public string disapproved_reason { get; set; }
        public string disapproved_by { get; set; }
        public string disapproved_desig { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string updated_by { get; set; }
    }
}
