//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leave_application_hdr_tbl
    {
        public string leave_ctrlno { get; set; }
        public string empl_id { get; set; }
        public Nullable<System.DateTime> date_applied { get; set; }
        public string leave_comments { get; set; }
        public string leave_type_code { get; set; }
        public string leave_subtype_code { get; set; }
        public Nullable<decimal> number_of_days { get; set; }
        public Nullable<decimal> sl_restore_deduct { get; set; }
        public Nullable<decimal> vl_restore_deduct { get; set; }
        public Nullable<decimal> oth_restore_deduct { get; set; }
        public Nullable<bool> leave_class { get; set; }
        public string leave_descr { get; set; }
        public string details_remarks { get; set; }
        public string approval_status { get; set; }
        public Nullable<bool> posting_status { get; set; }
        public string approval_id { get; set; }
        public Nullable<bool> justification_flag { get; set; }
        public string commutation { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by_user { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by_user { get; set; }
        public Nullable<System.DateTime> leaveledger_date { get; set; }
        public Nullable<decimal> leaveledger_balance_as_of_sl { get; set; }
        public Nullable<decimal> leaveledger_balance_as_of_vl { get; set; }
        public Nullable<decimal> leaveledger_balance_as_of_oth { get; set; }
        public Nullable<decimal> leaveledger_balance_as_of_sp { get; set; }
        public Nullable<decimal> leaveledger_balance_as_of_fl { get; set; }
        public Nullable<decimal> sp_restore_deduct { get; set; }
        public Nullable<decimal> fl_restore_deduct { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public string employment_type { get; set; }
        public string department_code { get; set; }
        public string department_short_name { get; set; }
        public string position_long_title { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public string suffix_name { get; set; }
        public string courtisy_title { get; set; }
        public string postfix_name { get; set; }
    }
}
