//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leave_application_signatories_tbl
    {
        public string sig_ctrlno { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public string effective_status { get; set; }
        public string leavetype_code { get; set; }
        public string sig_level { get; set; }
        public string empl_id { get; set; }
        public string sig_position { get; set; }
        public string sig_position_ovrd { get; set; }
        public Nullable<int> minimum_days { get; set; }
        public Nullable<int> maximum_days { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by_user { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by_user { get; set; }
    }
}
