//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leave_application_mone_tbl
    {
        public int id { get; set; }
        public string leave_ctrlno { get; set; }
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public Nullable<double> nbr_vl_remain { get; set; }
        public Nullable<double> nbr_fl_remain { get; set; }
        public Nullable<double> nbr_sl_remain { get; set; }
        public Nullable<double> nbr_min_mone { get; set; }
        public Nullable<double> nbr_max_mone { get; set; }
        public string department_code { get; set; }
        public string department_short_name { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public Nullable<decimal> allocated_mone { get; set; }
        public string mone_type { get; set; }
        public Nullable<double> nbr_mone { get; set; }
        public Nullable<decimal> total_mone { get; set; }
        public string remarks { get; set; }
        public Nullable<double> deduct_nbr_vl { get; set; }
        public Nullable<double> deduct_nbr_fl { get; set; }
        public Nullable<double> deduct_nbr_sl { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string updated_by { get; set; }
    }
}
