//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leave_application_mone_waiver_tbl
    {
        public int id { get; set; }
        public string leave_ctrlno { get; set; }
        public string empl_id { get; set; }
        public string empl_id_waiver { get; set; }
        public string employee_name { get; set; }
        public string department_code { get; set; }
        public string department_short_name { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public Nullable<decimal> allocated_mone { get; set; }
        public Nullable<decimal> total_waive_amount { get; set; }
        public string approval_status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string updated_by { get; set; }
    }
}
