//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaveappl_hdr_tbl
    {
        public string leave_ctrlno { get; set; }
        public string empl_id { get; set; }
        public Nullable<System.DateTime> date_filed { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public string empl_id_requestor { get; set; }
        public string leave_comments { get; set; }
        public string leave_type_code { get; set; }
        public string leave_subtype_code { get; set; }
        public Nullable<double> number_of_days { get; set; }
        public Nullable<double> vl_restore_deduct { get; set; }
        public Nullable<bool> leave_class { get; set; }
        public string leave_descr { get; set; }
        public string details_remarks { get; set; }
        public string approval_status { get; set; }
        public Nullable<bool> posting_status { get; set; }
        public string approval_id { get; set; }
        public Nullable<bool> justification_flag { get; set; }
    }
}
