//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lv_ledger_hdr_reprint_tbl
    {
        public int id { get; set; }
        public string ledger_ctrl_no { get; set; }
        public string empl_id { get; set; }
        public string reprint_reason { get; set; }
        public Nullable<System.DateTime> reprint_date_from { get; set; }
        public Nullable<System.DateTime> reprint_date_to { get; set; }
        public string reprint_status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_dttm { get; set; }
    }
}
