//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lv_ledger_summary
    {
        public int id { get; set; }
        public string empl_id { get; set; }
        public string leaveledger_period { get; set; }
        public string leavetype_str { get; set; }
        public string leavetype_code { get; set; }
        public string leavesubtype_code { get; set; }
        public string leaveledger_particulars { get; set; }
        public Nullable<decimal> vl_earned { get; set; }
        public Nullable<decimal> vl_wp { get; set; }
        public Nullable<decimal> vl_bal { get; set; }
        public Nullable<decimal> vl_wop { get; set; }
        public Nullable<decimal> sl_earned { get; set; }
        public Nullable<decimal> sl_wp { get; set; }
        public Nullable<decimal> sl_bal { get; set; }
        public Nullable<decimal> sl_wop { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by { get; set; }
    }
}
