//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lv_ledger_dtl_tbl
    {
        public string ledger_ctrl_no { get; set; }
        public string leavetype_code { get; set; }
        public string leavesubtype_code { get; set; }
        public Nullable<decimal> leaveledger_balance_as_of { get; set; }
        public Nullable<decimal> leaveledger_restore_deduct { get; set; }
        public Nullable<decimal> leaveledger_abs_und_wp { get; set; }
        public Nullable<decimal> leaveledger_abs_und_wop { get; set; }
    }
}
