//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lv_ledger_hdr_tbl
    {
        public string ledger_ctrl_no { get; set; }
        public string empl_id { get; set; }
        public Nullable<System.DateTime> leaveledger_date { get; set; }
        public string leaveledger_period { get; set; }
        public string leavetype_code { get; set; }
        public string leavesubtype_code { get; set; }
        public string leaveledger_particulars { get; set; }
        public string leaveledger_entry_type { get; set; }
        public string details_remarks { get; set; }
        public string approval_status { get; set; }
        public string approval_id { get; set; }
        public string leave_ctrlno { get; set; }
        public Nullable<System.DateTime> date_applied { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by_user { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by_user { get; set; }
        public string sig_name3_ovrd { get; set; }
        public string sig_pos3_ovrd { get; set; }
        public Nullable<decimal> lv_nodays { get; set; }
        public string lwop_date { get; set; }
        public string lwop_body_1 { get; set; }
        public string lwop_body_2 { get; set; }
    }
}
