//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lv_ledger_history_tbl
    {
        public int id { get; set; }
        public string ledger_ctrl_no { get; set; }
        public string leave_ctrlno { get; set; }
        public string appl_status { get; set; }
        public string appl_remarks { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by { get; set; }
    }
}
