//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lv_ledger_hdr_oth_tbl
    {
        public int id { get; set; }
        public string ledger_ctrl_no { get; set; }
        public string empl_id { get; set; }
        public Nullable<bool> ishide_ledger_row { get; set; }
    }
}
