//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthly_working_hrs_tbl
    {
        public string work_hrs_year { get; set; }
        public string work_hrs_month { get; set; }
        public string max_wrk_hrs { get; set; }
        public string min_wrk_hrs { get; set; }
        public string actual_wrk_hrs { get; set; }
        public Nullable<bool> within_capitol { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by_user { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by_user { get; set; }
    }
}
