//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newstepincrement_tbl
    {
        public string empl_id { get; set; }
        public System.DateTime date_generated { get; set; }
        public Nullable<System.DateTime> date_of_effectivity { get; set; }
        public string item_no { get; set; }
        public Nullable<int> step_increment_new { get; set; }
        public string approval_status { get; set; }
        public Nullable<bool> posting_status { get; set; }
        public string approval_id { get; set; }
        public string budget_code { get; set; }
        public string created_by_user { get; set; }
        public string updated_by_user { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string step_type { get; set; }
        public string salary_grade { get; set; }
    }
}
