//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ot_request_empl_dtl_tbl
    {
        public string ot_ctrl_no { get; set; }
        public string empl_id { get; set; }
        public string rcrd_status { get; set; }
    }
}
