//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollemployeemaster_pos_tbl
    {
        public string empl_id { get; set; }
        public string employment_type { get; set; }
        public System.DateTime effective_date { get; set; }
        public string position_code { get; set; }
        public Nullable<decimal> hazard_pay_override { get; set; }
    }
}
