//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollemployeemaster_asg_tbl
    {
        public string empl_id { get; set; }
        public string employment_type { get; set; }
        public System.DateTime effective_date { get; set; }
        public string department_code { get; set; }
        public string subdepartment_code { get; set; }
        public string division_code { get; set; }
        public string section_code { get; set; }
        public string function_code { get; set; }
        public string fund_code { get; set; }
        public Nullable<bool> upd_master_flag { get; set; }
        public Nullable<bool> phic_flag { get; set; }
        public Nullable<bool> ss_appl_flag { get; set; }
    }
}
