//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_tbl
    {
        public string empl_id { get; set; }
        public string bir_tin { get; set; }
        public string empl_photo { get; set; }
        public string umid { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string csc_eligibility { get; set; }
        public Nullable<bool> emp_status { get; set; }
        public string civil_status { get; set; }
        public string status_details { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> date_original_appointment { get; set; }
        public string emp_height { get; set; }
        public string emp_weight { get; set; }
        public string citizenship { get; set; }
        public string birth_place { get; set; }
        public string maiden_name { get; set; }
        public string father_birth_place { get; set; }
        public string mother_birth_place { get; set; }
        public string empl_photo_img { get; set; }
        public string spouse_last_name { get; set; }
        public string spouse_first_name { get; set; }
        public string spouse_middle_name { get; set; }
        public string spouse_suffix_name { get; set; }
        public string spouse_occupation { get; set; }
        public string spouse_employer_name { get; set; }
        public string spouse_business_address { get; set; }
        public string spouse_tel_no { get; set; }
        public string father_last_name { get; set; }
        public string father_middle_name { get; set; }
        public string father_first_name { get; set; }
        public string father_suffix_name { get; set; }
        public string mother_last_name { get; set; }
        public string mother_middle_name { get; set; }
        public string mother_first_name { get; set; }
        public Nullable<bool> citizenship_type { get; set; }
        public Nullable<bool> citizenship_nature { get; set; }
        public string citizenship_country { get; set; }
        public Nullable<int> ethnicity_id { get; set; }
        public Nullable<int> religion_id { get; set; }
        public Nullable<int> pwd_type_id { get; set; }
        public string gender2 { get; set; }
    }
}
