//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnelstatutory_tbl
    {
        public string empl_id { get; set; }
        public Nullable<bool> stat_ques34a { get; set; }
        public Nullable<bool> stat_ques34b { get; set; }
        public string stat_ques34_dtl { get; set; }
        public Nullable<bool> stat_ques35a { get; set; }
        public string stat_ques35a_dtl { get; set; }
        public Nullable<bool> stat_ques35b { get; set; }
        public string stat_ques35b_dtls_date { get; set; }
        public string stat_ques35b_dtls_status { get; set; }
        public Nullable<bool> stat_ques36 { get; set; }
        public string stat_ques36_dtl { get; set; }
        public Nullable<bool> stat_ques37 { get; set; }
        public string stat_ques37_dtl { get; set; }
        public Nullable<bool> stat_ques38a { get; set; }
        public string stat_ques38a_dtl { get; set; }
        public Nullable<bool> stat_ques38b { get; set; }
        public string stat_ques38b_dtl { get; set; }
        public Nullable<bool> stat_ques39 { get; set; }
        public string stat_ques39_dtl { get; set; }
        public Nullable<bool> stat_ques40a { get; set; }
        public string stat_ques40a_dtl { get; set; }
        public Nullable<bool> stat_ques40b { get; set; }
        public string stat_ques40b_dtl { get; set; }
        public Nullable<bool> stat_ques40c { get; set; }
        public string stat_ques40c_dtl { get; set; }
        public string govt_issued_id { get; set; }
        public string govt_issued_id_nbr { get; set; }
        public string date_place_issuance { get; set; }
        public string department_code { get; set; }
        public string printing_date { get; set; }
    }
}
