//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantilla_tbl
    {
        public string budget_code { get; set; }
        public string employment_type { get; set; }
        public string item_no { get; set; }
        public string item_no_old { get; set; }
        public string position_code { get; set; }
        public string department_code { get; set; }
        public string subdepartment_code { get; set; }
        public string division_code { get; set; }
        public string section_code { get; set; }
        public string function_code { get; set; }
        public string fund_code { get; set; }
        public string salary_grade { get; set; }
        public Nullable<byte> step_increment_cy { get; set; }
        public Nullable<decimal> annual_salary_cy { get; set; }
        public Nullable<byte> step_increment_ny { get; set; }
        public Nullable<decimal> annual_salary_ny { get; set; }
        public Nullable<System.DateTime> next_step_increment_eff_date { get; set; }
        public Nullable<decimal> step_increment_annual_amount { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public Nullable<decimal> daily_rate { get; set; }
        public Nullable<decimal> hourly_rate { get; set; }
        public Nullable<bool> flag_bir_tax { get; set; }
        public Nullable<bool> flag_representation_allowance { get; set; }
        public Nullable<bool> flag_transportation_allowance { get; set; }
        public Nullable<bool> flag_13th_14th_month_pay { get; set; }
        public Nullable<bool> flag_cash_gift { get; set; }
        public Nullable<bool> flag_loyalty_bonus { get; set; }
        public Nullable<bool> flag_productivity_ei { get; set; }
        public Nullable<bool> flag_clothing_allowance { get; set; }
        public Nullable<bool> flag_subsistence_allowance { get; set; }
        public Nullable<bool> flag_laundry_allowance { get; set; }
        public Nullable<bool> flag_pera { get; set; }
        public Nullable<bool> flag_gsis { get; set; }
        public Nullable<bool> flag_philhealth { get; set; }
        public Nullable<bool> flag_sif { get; set; }
        public Nullable<bool> flag_hdmf { get; set; }
        public Nullable<bool> flag_hazard_pay { get; set; }
        public Nullable<decimal> hazard_pay_override { get; set; }
        public Nullable<decimal> loyalty_bonus_amount { get; set; }
        public string empl_id { get; set; }
        public string employment_status { get; set; }
        public Nullable<System.DateTime> date_latest_appointment { get; set; }
        public Nullable<System.DateTime> effective_date_sg { get; set; }
        public string rate_basis { get; set; }
        public Nullable<System.DateTime> effective_date_sg_ny { get; set; }
        public Nullable<decimal> monthly_rate_ny { get; set; }
        public Nullable<decimal> daily_rate_ny { get; set; }
        public Nullable<decimal> hourly_rate_ny { get; set; }
        public string unit_code { get; set; }
    }
}
