//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class positions_tbl
    {
        public string position_code { get; set; }
        public string position_title1 { get; set; }
        public string position_title2 { get; set; }
        public string position_short_title { get; set; }
        public string salary_grade { get; set; }
        public string csc_level { get; set; }
        public string position_long_title { get; set; }
        public string employment_type { get; set; }
        public string qs_eduction { get; set; }
        public string qs_work_experience { get; set; }
        public string qs_training { get; set; }
        public string qs_eligibility { get; set; }
    }
}
