//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solo_parent_tbl
    {
        public int id { get; set; }
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public string department_code { get; set; }
        public string department_short_name { get; set; }
        public string solo_parent_no { get; set; }
        public Nullable<System.DateTime> valid_until { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string updated_by { get; set; }
        public string solo_parent_category { get; set; }
        public string qualification_code { get; set; }
        public Nullable<int> valid_year { get; set; }
    }
}
