//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class step_reckoning_tbl
    {
        public int id { get; set; }
        public string empl_id { get; set; }
        public System.DateTime rekoning_date { get; set; }
        public int rekon_step { get; set; }
        public string position_code { get; set; }
        public string position_title { get; set; }
        public string department_code { get; set; }
        public string salary_grade { get; set; }
        public string rekon_tag { get; set; }
        public string remarks { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dttm { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
    }
}
