//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeentries_mysql_tbl
    {
        public System.DateTime dtr_date { get; set; }
        public string empl_id { get; set; }
        public string time_in_am { get; set; }
        public string time_out_am { get; set; }
        public string time_in_pm { get; set; }
        public string time_out_pm { get; set; }
        public Nullable<int> under_Time { get; set; }
        public string remarks_details { get; set; }
        public string time_ot_hrs { get; set; }
    }
}
