//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class time_schedule_empl_tbl
    {
        public System.DateTime tse_date { get; set; }
        public string empl_id { get; set; }
        public string tse_day_parent { get; set; }
        public string tse_in_am { get; set; }
        public string tse_out_am { get; set; }
        public string tse_in_pm { get; set; }
        public string tse_out_pm { get; set; }
        public string tse_month { get; set; }
        public string tse_year { get; set; }
        public string ts_code { get; set; }
    }
}
