//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class to_disapprove_comment
    {
        public string empl_id { get; set; }
        public string travel_order_no { get; set; }
        public string comment { get; set; }
        public string comment_dttm { get; set; }
        public string comment_by { get; set; }
        public string updated_dttm { get; set; }
        public string updated_by { get; set; }
    }
}
