//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class to_disapprove_reason_tbl
    {
        public string to_rson_ctrl_no { get; set; }
        public string to_reason { get; set; }
        public Nullable<long> no_use { get; set; }
    }
}
