//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class to_final_approver_tbl
    {
        public string user_id { get; set; }
        public Nullable<bool> read_auth { get; set; }
        public Nullable<bool> write_auth { get; set; }
        public Nullable<int> access_type { get; set; }
        public string department_code { get; set; }
    }
}
