//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transmittal_leave_hdr_tbl
    {
        public string doc_ctrl_nbr { get; set; }
        public string transmittal_descr { get; set; }
        public Nullable<System.DateTime> approved_period_from { get; set; }
        public Nullable<System.DateTime> approved_period_to { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string doc_status { get; set; }
        public string route_nbr { get; set; }
    }
}
