//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactionsref_tbl
    {
        public string transaction_code { get; set; }
        public string transaction_descr { get; set; }
        public Nullable<byte> level_of_approval { get; set; }
        public Nullable<bool> with_reviewer { get; set; }
        public string transaction_APR_page_name { get; set; }
        public string transaction_SS_page_name { get; set; }
        public Nullable<int> module_id { get; set; }
        public Nullable<bool> with_self_service { get; set; }
        public Nullable<bool> with_self_service_approval { get; set; }
    }
}
