//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transmittal_leave_trk_setup_tbl
    {
        public string route_nbr { get; set; }
        public string route_descr { get; set; }
        public string department_code_lvl1 { get; set; }
        public string department_code_lvl2 { get; set; }
        public string department_code_lvl3 { get; set; }
        public string department_code_lvl4 { get; set; }
    }
}
