//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class traveltype_tbl
    {
        public string travel_type_code { get; set; }
        public string travel_type_abbrv { get; set; }
        public string travel_type_descr { get; set; }
        public Nullable<bool> travel_type_hazard { get; set; }
    }
}
