//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class travel_order_ldnf_tbl
    {
        public string travel_order_no { get; set; }
        public Nullable<bool> ldnf { get; set; }
        public Nullable<bool> to_emergency { get; set; }
    }
}
