//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class travel_order_check_tbl
    {
        public string travel_order_no { get; set; }
        public string empl_id { get; set; }
        public Nullable<bool> approved_status { get; set; }
        public Nullable<System.DateTime> approved_dttm { get; set; }
        public string approved_by { get; set; }
    }
}
