//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class travelpurpose_tbl
    {
        public int ctrl_no { get; set; }
        public string travel_purpose { get; set; }
        public Nullable<bool> with_claims { get; set; }
        public Nullable<bool> with_ldnf { get; set; }
        public Nullable<bool> with_emergency { get; set; }
    }
}
