//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class travelordertype_empl_dtl_tbl
    {
        public string travel_order_no { get; set; }
        public string empl_id { get; set; }
        public string travel_type_code { get; set; }
        public System.DateTime travel_date { get; set; }
        public Nullable<System.DateTime> travel_date_to { get; set; }
        public string rcrd_status { get; set; }
    }
}
