//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vl_wop_tbl
    {
        public double no_days_present { get; set; }
        public Nullable<double> no_days_onleave_wop { get; set; }
        public Nullable<double> leavecredit_earned { get; set; }
    }
}
