//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vlslearned_dailybasis_tbl
    {
        public double no_days { get; set; }
        public Nullable<double> vl_earned { get; set; }
        public Nullable<double> sl_earned { get; set; }
    }
}
