//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher_tbl
    {
        public string payroll_year { get; set; }
        public string voucher_ctrl_nbr { get; set; }
        public string payroll_month { get; set; }
        public string payrolltemplate_code { get; set; }
        public Nullable<System.DateTime> voucher_period_from { get; set; }
        public Nullable<System.DateTime> voucher_period_to { get; set; }
        public string voucher_descr1 { get; set; }
        public string voucher_descr2 { get; set; }
        public string empl_id { get; set; }
        public Nullable<decimal> gross_pay { get; set; }
        public Nullable<decimal> net_pay { get; set; }
        public string rate_basis { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public Nullable<decimal> daily_rate { get; set; }
        public Nullable<decimal> hourly_rate { get; set; }
        public Nullable<double> no_of_days { get; set; }
        public Nullable<decimal> other_amt1 { get; set; }
        public Nullable<decimal> other_amt2 { get; set; }
        public Nullable<decimal> other_amt3 { get; set; }
        public Nullable<decimal> wtax { get; set; }
        public Nullable<decimal> lowp_amount_salary { get; set; }
        public Nullable<decimal> lowp_amount_pera { get; set; }
        public Nullable<decimal> gsis_gs { get; set; }
        public Nullable<decimal> gsis_ps { get; set; }
        public Nullable<decimal> sif_gs { get; set; }
        public Nullable<decimal> hdmf_gs { get; set; }
        public Nullable<decimal> hdmf_ps { get; set; }
        public Nullable<decimal> phic_gs { get; set; }
        public Nullable<decimal> phic_ps { get; set; }
        public Nullable<decimal> nhmfc_hsing { get; set; }
        public Nullable<decimal> nafc_svlf { get; set; }
        public Nullable<decimal> sss_ps { get; set; }
        public Nullable<decimal> hdmf_ps2 { get; set; }
        public Nullable<decimal> hdmf_mp2 { get; set; }
        public Nullable<decimal> philamlife_ps { get; set; }
        public Nullable<decimal> gsis_ehp { get; set; }
        public Nullable<decimal> gsis_hip { get; set; }
        public Nullable<decimal> gsis_ceap { get; set; }
        public Nullable<decimal> gsis_addl_ins { get; set; }
        public Nullable<decimal> gsis_conso_ln { get; set; }
        public Nullable<decimal> gsis_policy_reg_ln { get; set; }
        public Nullable<decimal> gsis_policy_opt_ln { get; set; }
        public Nullable<decimal> gsis_uoli_ln { get; set; }
        public Nullable<decimal> gsis_emergency_ln { get; set; }
        public Nullable<decimal> gsis_ecard_ln { get; set; }
        public Nullable<decimal> gsis_educ_asst_ln { get; set; }
        public Nullable<decimal> gsis_real_state_ln { get; set; }
        public Nullable<decimal> gsis_sos_ln { get; set; }
        public Nullable<decimal> gsis_help { get; set; }
        public Nullable<decimal> gsis_housing_ln { get; set; }
        public Nullable<decimal> hdmf_mpl_ln { get; set; }
        public Nullable<decimal> hdmf_hse_ln { get; set; }
        public Nullable<decimal> hdmf_cal_ln { get; set; }
        public Nullable<decimal> hdmf_loyalty_card { get; set; }
        public Nullable<decimal> nico_ln { get; set; }
        public Nullable<decimal> network_ln { get; set; }
        public Nullable<decimal> ccmpc_ln { get; set; }
        public string preparedby_name { get; set; }
        public string preparedby_designation { get; set; }
        public Nullable<System.DateTime> date_posted { get; set; }
        public string post_status { get; set; }
        public string voucher_nbr { get; set; }
        public string created_by_user { get; set; }
        public string updated_by_user { get; set; }
        public string posted_by_user { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string voucher_type { get; set; }
        public string claimant_name { get; set; }
        public string claimant_rel { get; set; }
        public Nullable<decimal> other_premium1 { get; set; }
        public Nullable<decimal> other_premium2 { get; set; }
        public Nullable<decimal> other_premium3 { get; set; }
        public Nullable<decimal> other_premium4 { get; set; }
        public Nullable<decimal> other_premium5 { get; set; }
        public Nullable<decimal> other_loan1 { get; set; }
        public Nullable<decimal> other_loan2 { get; set; }
        public Nullable<decimal> other_loan3 { get; set; }
        public Nullable<decimal> other_loan4 { get; set; }
        public Nullable<decimal> other_loan5 { get; set; }
        public Nullable<decimal> lates_mins_hrs { get; set; }
        public Nullable<decimal> lates_amount { get; set; }
        public Nullable<decimal> refund_sal_amt { get; set; }
        public string department_code_trk { get; set; }
        public string function_code_trk { get; set; }
        public string allotment_code_trk { get; set; }
        public string voucher_remarks { get; set; }
    }
}
