//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_all_applications
    {
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public string application_nbr { get; set; }
        public string application_date { get; set; }
        public string rcrd_status { get; set; }
        public string rcrd_status_descr { get; set; }
        public string oth_info { get; set; }
        public string transaction_code { get; set; }
        public string transaction_descr { get; set; }
    }
}
