//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_approvalworkflow_tbl
    {
        public string approval_id { get; set; }
        public string transaction_code { get; set; }
        public string transaction_descr { get; set; }
        public string approval_status { get; set; }
        public string approval_status_descr { get; set; }
        public byte approval_route_seq { get; set; }
        public string reviewed_comment { get; set; }
        public string level1_approval_comment { get; set; }
        public string level2_approval_comment { get; set; }
        public string final_approval_comment { get; set; }
        public string disapproval_comment { get; set; }
        public string cancel_pending_comment { get; set; }
        public string cancelled_comment { get; set; }
        public string user_id_creator { get; set; }
        public string employee_name_creator { get; set; }
        public string user_id_reviewer { get; set; }
        public string employee_name_reviewer { get; set; }
        public string user_id_level1_approver { get; set; }
        public string employee_name_level1_approver { get; set; }
        public string user_id_level2_approver { get; set; }
        public string employee_name_level2_approver { get; set; }
        public string user_id_final_approver { get; set; }
        public string employee_name_final_approver { get; set; }
        public string user_id_disapprover { get; set; }
        public string employee_name_disapprover { get; set; }
        public string user_id_cancel_pending { get; set; }
        public string employee_name_cancel_pending { get; set; }
        public string reviewed_date { get; set; }
        public string level1_approval_date { get; set; }
        public string level2_approval_date { get; set; }
        public string final_approval_date { get; set; }
        public string disapproval_date { get; set; }
        public string cancel_pending_date { get; set; }
        public string cancelled_date { get; set; }
        public string empl_id { get; set; }
        public string employee_name { get; set; }
    }
}
