//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lv_ledger_info_curr_vl_sl
    {
        public string empl_id { get; set; }
        public decimal leaveledger_balance_as_of_vl { get; set; }
        public decimal leaveledger_restore_deduct_vl { get; set; }
        public decimal leaveledger_abs_und_wp_vl { get; set; }
        public decimal leaveledger_abs_und_wop_vl { get; set; }
        public decimal leaveledger_balance_as_of_sl { get; set; }
        public decimal leaveledger_restore_deduct_sl { get; set; }
        public decimal leaveledger_abs_und_wp_sl { get; set; }
        public decimal leaveledger_abs_und_wop_sl { get; set; }
    }
}
