//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lv_info
    {
        public string dtr_date { get; set; }
        public string empl_id { get; set; }
        public System.DateTime leave_date_from { get; set; }
        public System.DateTime leave_date_to { get; set; }
        public decimal date_num_day { get; set; }
        public string leavetype_code { get; set; }
        public string leavetype_descr { get; set; }
        public string leave_comments { get; set; }
    }
}
