//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_leave_application_signatories_tbl_list
    {
        public string sig_ctrlno { get; set; }
        public string effective_date { get; set; }
        public string effective_status { get; set; }
        public string leavetype_code { get; set; }
        public string leavetype_descr { get; set; }
        public string sig_level { get; set; }
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public string employee_name_2 { get; set; }
        public string sig_position { get; set; }
        public string position_title1 { get; set; }
        public string position_title2 { get; set; }
        public string position_short_title { get; set; }
        public string position_long_title { get; set; }
        public string sig_position_ovrd { get; set; }
        public Nullable<int> minimum_days { get; set; }
        public Nullable<int> maximum_days { get; set; }
    }
}
