//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lv_ledger_info
    {
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public string employee_name_format2 { get; set; }
        public string ledger_ctrl_no { get; set; }
        public Nullable<System.DateTime> leaveledger_date { get; set; }
        public string leaveledger_period { get; set; }
        public string leaveledger_particulars { get; set; }
        public string leaveledger_entry_type { get; set; }
        public string details_remarks { get; set; }
        public string approval_status { get; set; }
        public string approval_id { get; set; }
        public string leave_ctrlno { get; set; }
        public System.DateTime date_applied { get; set; }
        public System.DateTime created_dttm { get; set; }
        public string created_by_user { get; set; }
        public System.DateTime updated_dttm { get; set; }
        public string updated_by_user { get; set; }
        public string sig_name3_ovrd { get; set; }
        public string sig_pos3_ovrd { get; set; }
        public string leavetype_code { get; set; }
        public string leavesubtype_code { get; set; }
        public decimal leaveledger_balance_as_of { get; set; }
        public decimal leaveledger_restore_deduct { get; set; }
        public decimal leaveledger_abs_und_wp { get; set; }
        public decimal leaveledger_abs_und_wop { get; set; }
        public string leavetype_descr { get; set; }
        public string leavesubtype_descr { get; set; }
        public double leavetype_maxperyear { get; set; }
        public decimal leaveledger_balance_current { get; set; }
    }
}
