//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_leave_appl_posting_indv_history
    {
        public string leave_ctrlno { get; set; }
        public string ledger_ctrl_no { get; set; }
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public string leavetype_descr { get; set; }
        public string leavesubtype_descr { get; set; }
        public string leave_dates { get; set; }
        public System.DateTime action_dttm { get; set; }
        public string action_user_id { get; set; }
        public string action_employee_name { get; set; }
        public string action_remarks { get; set; }
    }
}
