//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lv_ledger_info_rep
    {
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public string employee_name_format2 { get; set; }
        public string position_long_title { get; set; }
        public string position_short_title { get; set; }
        public string monthly_rate { get; set; }
        public string department_code { get; set; }
        public string department_short_name { get; set; }
        public string department_name1 { get; set; }
        public string ledger_ctrl_no { get; set; }
        public Nullable<System.DateTime> leaveledger_date { get; set; }
        public string leaveledger_period { get; set; }
        public string leaveledger_particulars { get; set; }
        public string leaveledger_entry_type { get; set; }
        public string details_remarks { get; set; }
        public string approval_status { get; set; }
        public string approval_id { get; set; }
        public string leave_ctrlno { get; set; }
        public System.DateTime date_applied { get; set; }
        public System.DateTime created_dttm { get; set; }
        public string created_by_user { get; set; }
        public System.DateTime updated_dttm { get; set; }
        public string updated_by_user { get; set; }
        public string sig_name3_ovrd { get; set; }
        public string sig_pos3_ovrd { get; set; }
        public string leavetype_code { get; set; }
        public string leavesubtype_code { get; set; }
        public decimal leaveledger_balance_as_of { get; set; }
        public decimal leaveledger_restore_deduct { get; set; }
        public decimal leaveledger_abs_und_wp { get; set; }
        public decimal leaveledger_abs_und_wop { get; set; }
        public string leavetype_descr { get; set; }
        public string leavesubtype_descr { get; set; }
        public decimal leaveledger_balance_as_of_vl { get; set; }
        public decimal leaveledger_abs_und_wp_vl { get; set; }
        public decimal leaveledger_abs_und_wop_vl { get; set; }
        public decimal leaveledger_balance_as_of_sl { get; set; }
        public decimal leaveledger_abs_und_wp_sl { get; set; }
        public decimal leaveledger_abs_und_wop_sl { get; set; }
        public Nullable<decimal> lv_vl_sl_bal_total { get; set; }
        public Nullable<decimal> lv_vl_sl_wp_total { get; set; }
        public Nullable<decimal> lv_vl_sl_wop_total { get; set; }
        public bool leave_class { get; set; }
        public string leave_specify { get; set; }
        public string commutation { get; set; }
        public decimal number_of_days { get; set; }
        public string leave_appl_approval_status { get; set; }
    }
}
