//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_leaveadmin_tbl_list
    {
        public string empl_id { get; set; }
        public string department_code { get; set; }
        public string department_name1 { get; set; }
        public string department_name2 { get; set; }
        public string department_proper_name { get; set; }
        public string rcrd_status { get; set; }
        public string rcrd_status_descr { get; set; }
        public string department_short_name { get; set; }
        public bool approver { get; set; }
    }
}
