//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lv_earn_compute
    {
        public string empl_id { get; set; }
        public string leavetype_code { get; set; }
        public Nullable<System.DateTime> leave_process_date { get; set; }
        public Nullable<System.DateTime> leaveledger_date { get; set; }
        public decimal leaveledger_balance_as_of_sl { get; set; }
        public decimal leaveledger_restore_deduct_sl { get; set; }
        public decimal leaveledger_abs_und_wp_sl { get; set; }
        public decimal leaveledger_abs_und_wop_sl { get; set; }
        public decimal leaveledger_balance_as_of_vl { get; set; }
        public decimal leaveledger_restore_deduct_vl { get; set; }
        public decimal leaveledger_abs_und_wp_vl { get; set; }
        public decimal leaveledger_abs_und_wop_vl { get; set; }
        public string leaveledger_entry_type { get; set; }
        public string leave_ctrlno { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_by_user { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_by_user { get; set; }
    }
}
