//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ot_request_dtr_info
    {
        public string dtr_date { get; set; }
        public Nullable<int> dtr_year { get; set; }
        public Nullable<int> dtr_month { get; set; }
        public string empl_id { get; set; }
        public string time_in_am { get; set; }
        public string time_out_am { get; set; }
        public string time_in_pm { get; set; }
        public string time_out_pm { get; set; }
        public string inputtype_code { get; set; }
        public string inputtype_sub_descr { get; set; }
        public string remarks { get; set; }
        public string appl_type { get; set; }
    }
}
