//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ot_info
    {
        public string dtr_date { get; set; }
        public string empl_id { get; set; }
        public Nullable<System.DateTime> ot_date_from { get; set; }
        public Nullable<System.DateTime> ot_date_to { get; set; }
        public string ot_start_time { get; set; }
        public string ot_start_ampm { get; set; }
        public string ot_end_time { get; set; }
        public string ot_end_ampm { get; set; }
        public string ot_remarks { get; set; }
        public int weekdays_flag { get; set; }
        public string weekdays_in { get; set; }
        public string weekdays_in_ampm { get; set; }
        public string weekdays_out { get; set; }
        public string weekdays_out_ampm { get; set; }
        public int weekend_flag { get; set; }
        public string weekend_in { get; set; }
        public string weekend_in_ampm { get; set; }
        public string weekend_out { get; set; }
        public string weekend_out_ampm { get; set; }
        public int holiday_flag { get; set; }
        public string holiday_in { get; set; }
        public string holiday_in_ampm { get; set; }
        public string holiday_out { get; set; }
        public string holiday_out_ampm { get; set; }
        public int dayoff_ot_flag { get; set; }
        public string dayoff_ot_in { get; set; }
        public string dayoff_ot_in_ampm { get; set; }
        public string dayoff_ot_out { get; set; }
        public string dayoff_ot_out_ampm { get; set; }
        public int ot_coc_credit_flag { get; set; }
    }
}
