//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_personnelnames_tbl_DTR
    {
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public string employee_name_format_2 { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string suffix_name { get; set; }
        public string courtisy_title { get; set; }
        public System.DateTime birth_date { get; set; }
        public bool emp_status { get; set; }
        public string gender { get; set; }
    }
}
