//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_eAATS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_to_info_daily_rep
    {
        public string dtr_date { get; set; }
        public string empl_id { get; set; }
        public System.DateTime travel_date { get; set; }
        public Nullable<System.DateTime> travel_date_to { get; set; }
        public string TO_travel_starttime { get; set; }
        public string TO_travel_starttime_ampm { get; set; }
        public string TO_travel_endtime { get; set; }
        public string TO_travel_endtime_ampm { get; set; }
        public string TO_travel_type_abbrv { get; set; }
        public string travel_order_no { get; set; }
    }
}
